patch up levels

diff --git a/bin/call_antsregistration b/bin/call_antsregistration
--- a/bin/call_antsregistration
+++ b/bin/call_antsregistration
@@ -5,6 +5,56 @@
 source call_bashhelper
 
 #-----------------------------------------------------------------------------
+# get levels from input
+count_elements() {
+  local str="$1"
+  local sep="$2"
+  local arr
+
+  if [[ -z ${sep} ]]; then
+    sep="x"
+  fi
+
+  # split into array on $sep
+  IFS="$sep" read -r -a arr <<< "$str"
+
+  # print the length
+  printf '%d\n' "${#arr[@]}"
+}
+
+
+#-----------------------------------------------------------------------------
+# validate extension
+function validate_extension {
+
+  local in_file="${1}"
+  ext_file="$(fetch_extension "${in_file}")"
+  if [[ "${ext_file}" == "gz" ]] || [[ "${ext_file}" == "nii" || "${ext_file}" == "mgz" ]]; then
+    # convert mgz to nii.gz
+    if [[ "${ext_file}" == "mgz" ]]; then
+
+      cmd=(
+        call_mriconvert
+        "${in_file}"
+      )
+
+      eval "${cmd[@]}"
+      if [[ $? -ne 0 ]]; then
+        echo "${cmd[@]} failed"
+        exit 1
+      fi  
+
+      in_file="${in_file/.${ext_file}/.nii.gz}"
+    fi
+  else
+    echo "Input must be a nii(.gz) or .mgz file, not \"${ext_file}\" (${in_file})"
+    exit 1
+  fi
+
+  echo "${in_file}"
+}
+
+#-----------------------------------------------------------------------------
 # Create help text
 function Usage {
     cat <<USAGE
@@ -41,21 +91,27 @@ Arguments:
                   flags. Defaults to '8x4x2x1' for a 4 stage registration, and reduces with every 
                   stage not done. So for 3 stages, it defaults to '4x2x1', down to '1' for 1stage.
   -j <cores>      number of cores to use; default = 1
-  -n <levels>     number of levels to use (default = 4)
+  -n <levels>     number of levels to use. Defaults to '4' and is adjusted based on whether the
+                  user specified smoothing sigmas, convergence, or shrink factors. E.g., if 2x1
+                  is specified as shrink factor, the number of levels is adjusted to 2. You do
+                  not need to specify '-n 2' again.
 
 Options:
   -h|--help       print this help text
   -v|--verbose    Turn on verbose
   --<metric>      Flag to use a given metric. Available options are: 
-                    - 'cc' (cross-correlation),    
-                    - 'mi', (mutual information) [default],
-                    - 'mattes',
-                    - 'ms' (mean squares),
-                    - 'demons', 
-                    - 'gc' (global correlation),
-                    - 'icp' (euclidian),
-                    - 'pse' (point-set expectation),
-                    - 'jhct' (jensen-havrda-charvet-tsallis),
+                  For instance, to use (default = 'mi'):
+                    - 'mi'          | mutual information
+                    - 'lin'         | linear
+                    - 'gen'         | GenericLabel
+                    - 'cc'          | cross-correlation)
+                    - 'mattes'      | mattes
+                    - 'ms'          | mean squares
+                    - 'demons'      | demons 
+                    - 'gc'          | global correlation
+                    - 'icp'         | euclidian
+                    - 'pse'         | point-set expectation
+                    - 'jhct'        | jensen-havrda-charvet-tsallis
                     - 'igdm'
                     
                   By default, 'Cross-correlation' is used for SyN-diffeomorphic registration (the 
@@ -63,10 +119,17 @@ Options:
                   be altered.
   --fsl           also output the matrix in FSL-compatible format (not available for SyN)
   --itk           open ITK-Snap to verify how registration went
-  --<interp>      interpolation type: 'lin' (linear), 'nn' (NearestNeighbor), mul (MultiLabel),   
-                  gau (Gaussian), bspl<order>, cws (CosineWindowedSinc), wws (WelchWindowedSinc),
-                  hws (HammingWindowedSinc), lws (LanczosWindowedSinc), gen (GenericLabel);
-                  default = 'nn'
+  --<interp>      interpolation type (default = 'lin'):
+                    - 'lin'         | linear
+                    - 'nn'          | NearestNeighbor
+                    - 'mul'         | MultiLabel
+                    - 'gau'         | Gaussian
+                    - 'bspl<order>' | BSpline
+                    - 'cws'         | CosineWindowedSinc
+                    - 'wws'         | WelchWindowedSinc)
+                    - 'hws'         | HammingWindowedSinc
+                    - 'lws'         | LanczosWindowedSinc
+                    - 'gen'         | GenericLabel
 
                   For instance, to use:
                     - 'Linear' interpolation, use '--lin'
@@ -126,7 +189,7 @@ open_itk=0
 n_cpu=1
 as=0
 ras=1
-while getopts :-:hvi:t:x:n:s:c:r:g:j: argument
+while getopts :-:hvi:t:x:s:c:r:g:j:n: argument
 do
   case ${argument} in
     -)
@@ -241,15 +304,18 @@ do
           ;;
     x)  mask=${OPTARG}
           ;;
+    n)  n_levels=${OPTARG}
+          ;;          
     i)  initial=${OPTARG}
           ;;
-    n)  n_levels=${OPTARG}
-          ;;   
     s)  smooth=${OPTARG}
+        n_levels=$(count_elements "${smooth}")
           ;;   
     c)  converg=${OPTARG}
+        n_levels=$(count_elements "${converg}")
           ;;   
     r)  shrink=${OPTARG}
+        n_levels=$(count_elements "${shrink}")
           ;;            
     g)  gradient_step=${OPTARG}
           ;;     
@@ -263,24 +329,24 @@ done
 
 #-----------------------------------------------------------------------------
 # set number of cores to use
-export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=${n_cpu}
+export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS="${n_cpu}"
 
 #-----------------------------------------------------------------------------
 # function to derive the convergence, smoothing, shrinking parameters.
 function check_stage_inputs {
   
   in_type=${1}
-  if [[ ${in_type} == "converge" ]]; then
-    arr=${converg}
+  if [[ "${in_type}" == "converge" ]]; then
+    arr="${converg}"
     defaults=1000x500x250x100
-  elif [[ ${in_type} == "shrink" ]]; then
-    arr=${shrink}
+  elif [[ "${in_type}" == "shrink" ]]; then
+    arr="${shrink}"
     defaults=8x4x2x1
-  elif [[ ${in_type} == "smooth" ]]; then
-    arr=${smooth}
+  elif [[ "${in_type}" == "smooth" ]]; then
+    arr="${smooth}"
     defaults=3x2x1x0
   else
-    echo -e "${BOLD_RED}ERROR${RESET} in $(basename ${0}): unknown input type \"${in_type}\". Must be one of \"converge\", \"shrink\", or \"smooth\""
+    echo "Unknown input type \"${in_type}\". Must be one of \"converge\", \"shrink\", or \"smooth\""
     exit 1
   fi
   
@@ -305,73 +371,16 @@ function check_stage_inputs {
   else
     read -r -a parsed <<< "$arr"
     if [[ ${#parsed[@]} -ne ${n_levels} ]]; then
-      echo "  Got more values for \"${in_type}\" ($(echo ${arr})) than levels ($n_levels)"
+      echo "Got more values for \"${in_type}\" ($(echo ${arr})) than levels ($n_levels)"
       exit 1
     else
-      par=${arr}
+      par="${arr}"
     fi
   fi
 
   unset IFS
-  echo ${par}
+  echo "${par}"
 }
-
-#-----------------------------------------------------------------------------
-function validate_extension {
-
-  in_file="${1}"
-  ext_file=$(fetch_extension "${in_file}")
-  if [[ ${ext_file} == "gz" ]] || [[ ${ext_file} == "nii" ]]; then
-    :
-  else
-    # convert mgz to nii.gz
-    if [[ ${ext_file} == "mgz" ]]; then
-
-      call_mriconvert "${in_file}"
-      if [[ $? -ne 0 ]]; then
-        print_error_msg "$(basename ${0})" "call_mriconvert"
-        exit 1
-      fi  
-
-      in_file="${in_file/.${ext_file}/.nii.gz}"
-    else
-      echo
-      print_line -
-      print_error_msg "$(basename ${0})" "input" "Input must be a nii(.gz) or .mgz file, not \"${ext_file}\""
-      exit 1
-    fi
-  fi
-
-  echo "${in_file}"
-}
-
-#-----------------------------------------------------------------------------
-# check if we got custom inputs, whether we should use defaults, and whether specified values 
-# match the number of levels specified if check_stage_inputs fails, the returned value will be the 
-# error message, so we can conveniently make a traceback
-shrink=$(check_stage_inputs shrink)
-if [[ $? -ne 0 ]]; then
-  echo
-  print_line -
-  print_error_msg "$(basename ${0})" "check_stage_inputs" "Shrink inputs not correct: ${shrink}"
-  exit 1
-fi
-
-converg=$(check_stage_inputs converge)
-if [[ $? -ne 0 ]]; then
-  echo
-  print_line -
-  print_error_msg "$(basename ${0})" "check_stage_inputs" "Converging inputs not correct: ${converg}"
-  exit 1
-fi
-
-smooth=$(check_stage_inputs smooth)
-if [[ $? -ne 0 ]]; then
-  echo
-  print_line -
-  print_error_msg "$(basename ${0})" "check_stage_inputs" "Smoothing inputs not correct: ${smooth}"
-  exit 1
-fi
 
 if [[ $# -lt 3 ]] ; then
   Usage && exit 0
@@ -391,7 +400,7 @@ if [[ ! -f "${REF}" ]]; then
   print_error_msg "$(basename ${0})" "find" "Could not find FIXED image \"${BOLD_GREEN}${REF}${RESET}\""
   exit 1
 else
-  REF=$(readlink "${REF}")
+  REF=$(readlink -f "${REF}")
 fi
 
 if [[ ! -f "${MOV}" ]]; then
@@ -411,6 +420,34 @@ if [[ -z "${OUT}" ]]; then
 fi
 
 #-----------------------------------------------------------------------------
+# check if we got custom inputs, whether we should use defaults, and whether specified values 
+# match the number of levels specified if check_stage_inputs fails, the returned value will be the 
+# error message, so we can conveniently make a traceback
+shrink="$(check_stage_inputs shrink)"
+if [[ $? -ne 0 ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" "check_stage_inputs" "Shrink inputs not correct: ${shrink}"
+  exit 1
+fi
+
+converg="$(check_stage_inputs converge)"
+if [[ $? -ne 0 ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" "check_stage_inputs" "Converging inputs not correct: ${converg}"
+  exit 1
+fi
+
+smooth="$(check_stage_inputs smooth)"
+if [[ $? -ne 0 ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" "check_stage_inputs" "Smoothing inputs not correct: ${smooth}"
+  exit 1
+fi
+
+#-----------------------------------------------------------------------------
 # set flag to extract first volume from 4D image to 0
 extract_fixed=0
 extract_moving=0
@@ -424,7 +461,7 @@ REF=$(validate_extension "${REF}")
 if [[ $? -ne 0 ]]; then
   echo
   print_line -
-  print_error_msg "$(basename ${0})" "validate_extension"
+  print_error_msg "$(basename ${0})" "validate_extension" "${REF}"
   exit 1
 fi
 
@@ -432,7 +469,7 @@ MOV=$(validate_extension "${MOV}")
 if [[ $? -ne 0 ]]; then
   echo
   print_line -
-  print_error_msg "$(basename ${0})" "validate_extension"
+  print_error_msg "$(basename ${0})" "validate_extension" "${REF}"
   exit 1
 fi
 
@@ -600,7 +637,7 @@ function syn_ {
 }
 
 # add individual stages
-type_lower=$(printf '%s' "${TYPE}" | tr '[:upper:]' '[:lower:]')
+type_lower=$(make_lower "${TYPE}")
 if [[ "${type_lower}" == "rigid" ]]; then
   cmd+=" $(rigid_)"
 elif [[ "${type_lower}" == "affine" ]]; then
@@ -628,7 +665,7 @@ fi
 
 # echo command to text file
 cmd_f="${OUT}command.txt"
-rm ${cmd_f} 2>/dev/null
+rm "${cmd_f}" 2>/dev/null
 echo "${cmd}" >> "${cmd_f}"
 
 # Execute command
