[ENH]: stability argparser

diff --git a/bin/call_fmriprep b/bin/call_fmriprep
--- a/bin/call_fmriprep
+++ b/bin/call_fmriprep
@@ -1,5 +1,57 @@
 #!/usr/bin/env bash
 
+parse_extra_sets() {
+    local input=$1
+    local -n output=$2
+    local item
+
+    output=()
+
+    IFS=',' read -r -a raw_items <<< "$input"
+
+    for item in "${raw_items[@]}"; do
+        # Trim surrounding whitespace only.
+        item="${item#"${item%%[![:space:]]*}"}"
+        item="${item%"${item##*[![:space:]]}"}"
+
+        [[ -n $item ]] && output+=("$item")
+    done
+}
+
+remove_cmd_flag() {
+  local array_name=$1
+  local target_flag=$2
+  local takes_value=$3
+  local -n args_ref="$array_name"
+
+  local -a filtered=()
+  local i arg current_flag
+
+  for ((i = 0; i < ${#args_ref[@]}; i++)); do
+    arg=${args_ref[i]}
+    current_flag=${arg%%=*}
+
+    if [[ $current_flag == "$target_flag" ]]; then
+      # Existing --flag=value form.
+      if [[ $arg == *=* ]]; then
+        continue
+      fi
+
+      # Existing --flag value form.
+      if [[ $takes_value == 1 ]] &&
+         ((i + 1 < ${#args_ref[@]})); then
+        ((i++))
+      fi
+
+      continue
+    fi
+
+    filtered+=("$arg")
+  done
+
+  args_ref=("${filtered[@]}")
+}
+
 #-----------------------------------------------------------------------------
 # Get bash helper functions
 source call_bashhelper
@@ -39,7 +91,7 @@ Optional arguments:
                   Default: \$PATH_HOME/fmriprep/\$PROJECT
   -l <license>    FreeSurfer license file. When using Singularity, this path must be
                   accessible from within the bind path
-  -x <config>     BIDS filter file passed to fMRIPrep with --bids-filter-file
+  -y <config>     BIDS filter file passed to fMRIPrep with --bids-filter-file
   -t <task ID>    restrict preprocessing to one task using --task-id
   -k <kwargs>     text file with additional fMRIPrep arguments, one argument or
                   argument-value pair per line
@@ -47,6 +99,13 @@ Optional arguments:
                   BOLD files should be kept. By default, generated MNI152
                   preprocessed BOLD NIfTIs are removed to save disk space while
                   transformation files are retained. Use '-a all' to keep all runs
+  -x <kwargs>     additional arguments passed to call_fmriprep / fMRIprep (alternative
+                  to '-k <kwargs_file>' flag). Format should be comma-separated flags:
+                    - flag with value: <flag>=<value>
+                    - flag only:       <flag>
+
+                  Example:
+                    -x "--derivatives=/path/to/derivatives,----bold2t1w-init=header"
 
 Options:
   -h|--help       print this help text
@@ -58,6 +117,7 @@ Options:
                   previous intermediate results
   --try           do not pass --stop-on-first-crash. This lets fMRIPrep continue after
                   recoverable errors, but failed nodes should still be inspected
+  --dry-run       print final fmriprep-command to-be-executed
 
 Example:
   call_fmriprep -s 001
@@ -104,8 +164,9 @@ work="${PATH_HOME}/fmriprep/${PROJECT}"
 KWARGS_FILE=""
 clean_wd=0
 USE_DOCKER=0
+dryrun=0
 crash_flag="--stop-on-first-crash"
-while getopts :-:hus:m:r:d:c:i:b:w:l:x:t:k:a: arg
+while getopts :-:hus:m:r:d:c:i:b:w:l:x:t:k:a:y: arg
 do
   case ${arg} in
     -)
@@ -118,6 +179,9 @@ do
         docker)
           USE_DOCKER=1
           ;; 
+        debug)
+          dryrun=1
+          ;;           
         clean)
           clean_wd=1
           ;;  
@@ -150,8 +214,10 @@ do
           ;;
     l)  LIC="${OPTARG}"
           ;;
-    x)  CONFIG="${OPTARG}"
+    y)  CONFIG="${OPTARG}"
           ;;
+    x)  KWARGS_FLAG="${OPTARG}"
+          ;;          
     t)  TASK_ID="${OPTARG}"
           ;;
     k)  KWARGS_FILE="${OPTARG}"
@@ -180,7 +246,7 @@ fi
 # check kwargs file
 if [[ ! -z "${KWARGS_FILE}" ]]; then
 
-  echo "Including kwargs from \"${KWARGS_FILE}\":"  
+  echo "Including kwargs from ${BOLD_GREEN}${KWARGS_FILE}${RESET}:"  
   
   # exclude these flags; these should be specified in spinoza_setup or command line
   flags_from_setup=(
@@ -248,6 +314,8 @@ if [[ ! -d "${work}" ]]; then
   mkdir -p "${work}"
 fi
 
+workdir_flag=(--work-dir "${work}")
+
 #-----------------------------------------------------------------------------
 # Set default FS-license if none specified
 if [[ ! -z "${FS_LICENSE}" ]]; then
@@ -262,25 +330,25 @@ fi
 #-----------------------------------------------------------------------------
 # Check if we need to output CIFTIs
 if [[ ! -z "${CIFTI}" ]]; then
-  cifti_flag="--cifti-output ${CIFTI}"
+  cifti_flag=(--cifti-output "${CIFTI}")
 fi
 
 #-----------------------------------------------------------------------------
 # Check if we received configuration file
 if [[ ! -z "${CONFIG}" ]]; then
-  config_flag="--bids-filter-file ${CONFIG}"
+  config_flag=(--bids-filter-file "${CONFIG}")
 fi
 
 #-----------------------------------------------------------------------------
 # Check if we received task ID
 if [[ ! -z "${TASK_ID}" ]]; then
-  task_flag="--task-id ${TASK_ID}"
+  task_flag=(--task-id "${TASK_ID}")
 fi
 
 #-----------------------------------------------------------------------------
 # Check if we need to output CIFTIs
 if [[ ${DO_SYN} -eq 1 ]]; then
-  syn_flag="--use-syn-sdc"
+  syn_flag=(--use-syn-sdc)
 fi
 
 #-----------------------------------------------------------------------------
@@ -300,7 +368,7 @@ fi
 #-----------------------------------------------------------------------------
 # Define command line
 if [[ ${USE_DOCKER} -eq 1 ]]; then
-  run_cmd="fmriprep-docker"
+  run_cmd=("fmriprep-docker")
 else
   if [[ -f "${fprep_container}" ]]; then
 
@@ -329,24 +397,38 @@ else
     fi
 
     # define SGE command |  -B /mnt/d/fMRI/HRA/nipype.cfg:/home/fmriprep/.nipype/nipype.cfg:ro
-    run_cmd="singularity run --cleanenv -B ${binding}:${binding} ${fprep_container}"
+    run_cmd=(
+      singularity run
+      --cleanenv
+      -B "${binding}:${binding}"
+      "${fprep_container}"
+    )
 
   else
     echo "WARNING: system is setup to use singularity, but image \"${fprep_container}\" could not be found. Defaulting to \"fmriprep\"-command"
-    run_cmd="fmriprep"
+    run_cmd=("fmriprep")
   fi
 fi
 
 #-----------------------------------------------------------------------------
 # overwrite anat only if 'func' is specified
-use_output_spaces="${FPREP_OUTPUT_SPACES}"
-if [[ ${mode} != "anat" ]]; then
-  anat_only_flag=""
+read -r -a output_spaces <<< "${FPREP_OUTPUT_SPACES:-}"
+read -r -a anat_spaces <<< "${FPREP_ANAT_SPACES:-}"
+
+use_output_spaces=("${output_spaces[@]}")
+
+if [[ $mode == "anat" && ${#anat_spaces[@]} -gt 0 ]]; then
+  use_output_spaces=("${anat_spaces[@]}")
 else
-  if [[ ! -z "${FPREP_ANAT_SPACES}" ]]; then
-    use_output_spaces="${FPREP_ANAT_SPACES}"
-  fi
+  anat_only_flag=""
 fi
+
+output_space_flag=(
+    --output-spaces
+    "${use_output_spaces[@]}"
+)
+
+output_space_flag=(--output-spaces "${use_output_spaces[@]}")
 
 #-----------------------------------------------------------------------------
 # set nthreads
@@ -355,17 +437,18 @@ if [[ -z ${n_threads} ]]; then
 else
   nthreads=${n_threads}
 fi
-nthread_flag="--nthreads ${nthreads}"
+nthread_flag=(--nthreads "${nthreads}")
 
 #-----------------------------------------------------------------------------
 # output directory structure has changed after v21: https://github.com/nipreps/fmriprep/releases/tag/21.0.0
 echo "Checking fMRIPrep's version.."
-version_string=$(eval ${run_cmd} --version)
-if [[ $? -ne 0 ]]; then
+if ! version_string=$("${run_cmd[@]}" --version); then
   echo
   print_line -
-  print_error_msg "$(basename ${0})" eval "Could not derive version:"
-  echo "${version}"
+  print_error_msg \
+    "$(basename "$0")" \
+    "${run_cmd[0]}" \
+    "Could not derive fMRIPrep version"
   exit 1
 fi
 
@@ -378,7 +461,7 @@ if [[ "${major_version}" -lt 21 ]]; then
   #-----------------------------------------------------------------------------
   # Check how to initialize bold-to-T1w registration
   if [[ ${BOLD_T1W_INIT} == "register" ]] || [[ ${BOLD_T1W_INIT} == "header" ]]; then
-    init_flag="--bold2t1w-init ${BOLD_T1W_INIT}"
+    init_flag=(--bold2t1w-init "${BOLD_T1W_INIT}")
   fi    
 else
   output_dir="${derivatives}/fmriprep"
@@ -391,39 +474,84 @@ else
     if [[ ${BOLD_T1W_INIT} == "register" ]]; then
       export BOLD_T1W_INIT="auto"
     fi
-    init_flag="--bold2anat-init ${BOLD_T1W_INIT}"
+    init_flag=(--bold2anat-init "${BOLD_T1W_INIT}")
   fi    
 fi
 
 #-----------------------------------------------------------------------------
 # define the fMRIPrep command
 cmd=(
-  "${run_cmd}"
+  "${run_cmd[@]}"
   "${project}"
   "${output_dir}"
   participant
   --participant-label "${subj_ID}"
   --skip-bids-validation
   --md-only-boilerplate
-  --fs-license-file "${license}"
-  --output-spaces "${use_output_spaces}"
   --fs-subjects-dir "${FS}"
-  --work-dir "${work}"
-  "${crash_flag}"
-  "${bbr_flag}"
-  "${cifti_flag}"
-  "${syn_flag}"
-  "${config_flag}"
-  "${task_flag}"
-  "${init_flag}"
-  "${anat_only_flag}"
-  "${nthread_flag}"
+  --fs-license-file "${license}"
+  "${output_space_flag[@]}"
+  "${workdir_flag[@]}"
+  "${init_flag[@]}"
   "${kwargs[@]}"
+  ${crash_flag:+"$crash_flag"}
+  ${bbr_flag:+"$bbr_flag"}
+  "${cifti_flag[@]}"
+  "${syn_flag[@]}"
+  "${config_flag[@]}"
+  "${task_flag[@]}"
+  ${anat_only_flag:+"$anat_only_flag"}
+  "${nthread_flag[@]}"
 )
 
 #-----------------------------------------------------------------------------
+# Use specified kwargs as final override
+if [[ -n ${KWARGS_FLAG:-} ]]; then
+
+  # parse kwargs
+  parse_extra_sets "$KWARGS_FLAG" extra_sets
+
+  for override in "${extra_sets[@]}"; do
+    if [[ $override == *=* ]]; then
+      override_flag=${override%%=*}
+      override_value=${override#*=}
+
+      remove_cmd_flag cmd "$override_flag" 1
+      cmd+=("$override_flag" "$override_value")
+    else
+      override_flag=$override
+
+      remove_cmd_flag cmd "$override_flag" 0
+      cmd+=("$override_flag")
+    fi
+  done
+fi
+
+# clean up
+clean_cmd=()
+for arg in "${cmd[@]}"; do
+    [[ -n $arg ]] && clean_cmd+=("$arg")
+done
+
+cmd=("${clean_cmd[@]}")
+
+if [[ ${dryrun} -eq 1 ]]; then
+
+  # print normally
+  print_cmd "${cmd[@]}"
+  echo
+
+  # print flag-argument binder
+  for i in "${!cmd[@]}"; do
+    printf 'cmd[%2d] = <%q>\n' "$i" "${cmd[$i]}"
+  done
+
+  exit 0
+fi
+
+#-----------------------------------------------------------------------------
 # execute
-print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+print_cmd "${cmd[@]}" && "${cmd[@]}"
 
 if [[ $? -ne 0 ]]; then
   echo
diff --git a/shell/spinoza_fmriprep b/shell/spinoza_fmriprep
--- a/shell/spinoza_fmriprep
+++ b/shell/spinoza_fmriprep
@@ -90,7 +90,8 @@ manage_fmriprep_workdir() {
   local remove_surf_wf="$4"
   local remove_wf="$5"
   local overwrite="$6"
-  local runs=("${@:7}")  # Capture remaining arguments as an array
+  local local_bool="$7"
+  local runs=("${@:8}")  # Capture remaining arguments as an array
 
   # Ensure working directory exists
   if [[ ! -d "${workdir}" ]]; then
@@ -122,24 +123,35 @@ manage_fmriprep_workdir() {
       if [[ "${remove_surf_wf}" -eq 1 ]]; then
         surf_wf=$(find "${subj_wf}" -type d -name "surface_recon_wf")
         if [[ -d "${surf_wf}" ]]; then
-          echo -e "Removing ${BOLD_MAGENTA}${surf_wf}${RESET}"
+          if [[ ${local_bool} -eq 1 ]]; then
+            echo -e "Execute [reason]: Removing ${BOLD_MAGENTA}${surf_wf}${RESET}"
+          fi
           rm -r "${surf_wf}" 2>/dev/null
         else
-          echo -e "Could not find ${BOLD_RED}surface_recon_wf${RESET} folder in ${BOLD_MAGENTA}${subj_wf}${RESET}"
+          if [[ ${local_bool} -eq 1 ]]; then
+            echo -e "Execute [reason]: Could not find ${BOLD_RED}surface_recon_wf${RESET} folder in ${BOLD_MAGENTA}${subj_wf}${RESET}"
+          fi
         fi
       # remove full workflow (BOLD, FMAP, & ANAT)
       elif [[ "${remove_wf}" -eq 1 ]]; then
-        echo -e "Removing ${BOLD_MAGENTA}${subj_wf}${RESET}"
+        if [[ ${local_bool} -eq 1 ]]; then
+          echo -e "Execute [reason]: Removing ${BOLD_MAGENTA}${subj_wf}${RESET}"
+        fi
         rm -r "${subj_wf}" 2>/dev/null
       # Remove workflow folders for specific runs or all runs
       elif [[ "${overwrite}" -eq 1 ]]; then
         if [[ ${#runs[@]} -gt 0 ]]; then
           for r in "${runs[@]}"; do
-            echo -e "Removing workflow folders with ${BOLD_RED}run-${r}${RESET} in ${BOLD_MAGENTA}${subj_wf}${RESET}"
+            if [[ ${local_bool} -eq 1 ]]; then
+              echo -e "Execute [reason]: Removing workflow folders with ${BOLD_RED}run-${r}${RESET} in ${BOLD_MAGENTA}${subj_wf}${RESET}"
+            fi
             rm -r "${subj_wf}/"*run_"${r}"* 2>/dev/null
           done
         else
-          echo -e "Removing workflow folders with ${BOLD_RED}run-*${RESET} in ${BOLD_MAGENTA}${subj_wf}${RESET}"
+          if [[ ${local_bool} -eq 1 ]]; then
+            echo -e "Execute [reason]: Removing workflow folders with ${BOLD_RED}run-*${RESET} in ${BOLD_MAGENTA}${subj_wf}${RESET}"
+          fi
+
           local ddir
           ddir=(
             $(
@@ -154,72 +166,74 @@ manage_fmriprep_workdir() {
         fi
       fi
     else
-      echo -e "No folder with ${BOLD_RED}*_${sub_id}_wf${RESET} in ${BOLD_MAGENTA}${wf_folder}${RESET}"
+      if [[ ${local_bool} -eq 1 ]]; then
+        echo -e "Execute [reason]: No folder with ${BOLD_RED}*_${sub_id}_wf${RESET} in ${BOLD_MAGENTA}${wf_folder}${RESET}"
+      fi
     fi
   else
-    echo -e "No folder with ${BOLD_RED}-name "fmriprep*" -and -name "*wf"${RESET} in ${BOLD_MAGENTA}${workdir}${RESET}"
+    if [[ ${local_bool} -eq 1 ]]; then
+      echo -e "Execute [reason]: No folder with ${BOLD_RED}-name "fmriprep*" -and -name "*wf"${RESET} in ${BOLD_MAGENTA}${workdir}${RESET}"
+    fi
   fi
 }
 
 #-----------------------------------------------------------------------------
 # config file function
 generate_config_file() {
-  local conf="$1"
-  local runs=("${@:2}")  # Capture remaining arguments as an array
-  local confFile=""
+  local conf=$1
+  shift
+  local runs=("$@")
+  local conf_file=""
 
-  if [[ -z "${conf}" ]]; then
-    # If no config file is provided, check for run-specific files
-    if [[ ${#runs[@]} -gt 0 ]]; then
-      local run_="["
-      local r_ct=0
-      local workdir="${WORKDIR:-$DIR_DATA_HOME}"
+  if [[ -z $conf ]]; then
+    if ((${#runs[@]} > 0)); then
+      local workdir=${WORKDIR:-$DIR_DATA_HOME}
+      conf_file="${workdir}/run_conf.json"
 
-      for r in "${runs[@]}"; do
-        if [[ ${r_ct} -lt $((${#runs[@]} - 1)) ]]; then
-          run_+="${r},"
-        else
-          run_+="${r}]"
-        fi
-        ((r_ct++))
+      local run_json=""
+      local run
+
+      for run in "${runs[@]}"; do
+        printf -v run_json '%s"%s",' "$run_json" "$run"
       done
 
-      confFile="${workdir}/run_conf.json"
-      [[ -f "${confFile}" ]] && rm -f "${confFile}"
+      run_json="[${run_json%,}]"
 
-      # Generate JSON config file
-      cat <<EOF > "${confFile}"
+      cat > "$conf_file" <<EOF
 {
   "bold": {
-      "run": ${run_}
+    "run": $run_json
   },
   "fmap": {
-      "run": ${run_}
+    "run": $run_json
   }
 }
 EOF
-
-      confFile="-x ${confFile}"
     fi
   else
-    if [[ ${#runs[@]} -gt 0 ]]; then
-      echo "WARNING: Specific runs were requested, but a configuration file was also specified."
-      echo "Since merging these is tedious, please use the configuration file to select runs."
+    if ((${#runs[@]} > 0)); then
+      echo "WARNING: Specific runs and a configuration file were both provided." >&2
+      echo "The configuration file will determine run selection." >&2
 
       while true; do
-        read -p "Do you want to proceed? (yes/no) " yn
+        read -r -p "Do you want to proceed? (yes/no) " yn
         case $yn in
-          y|yes ) break ;;
-          n|no ) echo "Exiting..."; exit 1 ;;
-          * ) echo "Invalid response (use \"yes\"/\"y\" or \"no\"/\"n\")." ;;
+          y|yes) break ;;
+          n|no)
+            echo "Exiting..." >&2
+            return 1
+            ;;
+          *)
+            echo 'Invalid response; use "yes", "y", "no", or "n".' >&2
+            ;;
         esac
       done
     fi
-    confFile="-x ${conf}"
+
+    conf_file=$conf
   fi
 
-  # Return the config file variable (if needed)
-  echo "$confFile"
+  printf '%s\n' "$conf_file"
 }
 
 #-----------------------------------------------------------------------------
@@ -263,7 +277,7 @@ Arguments:
   -f <func dir>   directory containing functional data; used after running FreeSurfer outside of
                   fMRIprep <optional>
   -j <cpus>       number of cores to use (default is 1)
-  -k <kwargs>     specify a file with additional arguments, similar to FreeSurfer's expert options.
+  -k <file>       specify a file with additional arguments, similar to FreeSurfer's expert options.
                   See fmriproc/misc/fprep_options for an example. Please make sure you have a 
                   final empty white space at the end of the file, otherwise the parser gets confu-
                   sed. For VSCode: https://stackoverflow.com/a/44704969.
@@ -282,6 +296,13 @@ Arguments:
                   (in case another task is already done), use '-t <task_id>'.
   -u <config>     configuration file as specified in /misc/fmriprep_config?.json
   -w <workdir>    custom working directory; defaults to PATH_HOME/fmriprep/<PROJECT>
+  -x <kwargs>     additional arguments passed to call_fmriprep / fMRIprep. Format should be
+                  comma-separated flags:
+                    - flag with value: <flag>=<value>
+                    - flag only:       <flag>
+
+                  Example:
+                    -x "--derivatives=/path/to/derivatives,----bold2t1w-init=header"  
 
 Options:
   -h|--help       print this help text
@@ -360,7 +381,9 @@ crash_flag=""
 mode="anat"
 workdir="${PATH_HOME}/fmriprep/${PROJECT}"
 SGE_QUEUE="${SGE_QUEUE_LONG}"
-while getopts :-:hols:r:n:f:m:j:k:q:u:a:w: argument
+kwargs_flag=""
+dryrun_flag=""
+while getopts :-:hols:r:n:f:m:j:k:q:u:a:w:x: argument
 do
 case ${argument} in
     -)
@@ -374,6 +397,10 @@ case ${argument} in
         sge)
           run_local=0
           ;;
+        debug)
+          dryrun_flag="--debug"
+          run_local=1
+          ;;          
         remove-wf)
           remove_wf=1
           ;; 
@@ -416,7 +443,7 @@ case ${argument} in
           ;;
     j)  n_cpus="${OPTARG}"
           ;; 
-    k)  kwargs_file="-k ${OPTARG}"
+    k)  kwargs_file="${OPTARG}"
           ;;
     r)  runs="${OPTARG}"
           ;; 
@@ -424,20 +451,25 @@ case ${argument} in
           ;; 
     w)  workdir="${OPTARG}"
           ;; 
+    x)  kwargs_flag="${OPTARG}"
+          ;;           
     o)  OW=1
           ;;
-    a)  keep_runs="-a ${OPTARG}"
+    a)  keep_runs="${OPTARG}"
           ;; 
   esac
 done
 
-if [[ $# -lt 3 ]] ; then
-  Usage && exit 0
+shift "$((OPTIND - 1))"
+
+if (( $# < 3 )); then
+    Usage
+    exit 1
 fi
 
-INPUT="${@:$OPTIND:1}"
-OUTPUT="${@:$OPTIND+1:1}"
-T2="${@:$OPTIND+2:1}"
+INPUT=$1
+OUTPUT=$2
+T2=$3
 
 # check run
 if [[ ! -z ${runs} ]]; then
@@ -451,12 +483,12 @@ search=$(determine_subjects "$INPUT" "$SUBJECT_PREFIX" "$sub")
 # Check if ${mode} represents a task ID instead of "anat" or "func"
 task_id=""
 if [[ -n ${mode} && ${mode} != "anat" && ${mode} != "func" ]]; then
-  task_id="-t ${mode}"
+  task_id="${mode}"
 fi
 
-# reset input directory if docker is used
-if [[ ! -z ${docker_flag} ]]; then
-  INPUT="${func_dir}"
+# always run debugger locally
+if [[ -n $dryrun_flag ]]; then
+  run_local=1
 fi
 
 #-----------------------------------------------------------------------------
@@ -475,11 +507,12 @@ for subID in ${search}; do
 
   #-----------------------------------------------------------------------------
   # define input
-  input_dir="${INPUT}/${base_path}"
   if [[ "${mode}" == "anat" ]]; then
+    
     #-----------------------------------------------------------------------------
     # anat only
-    func_txt="Only including anatomical data"
+    input_dir="${INPUT}/${base_path}"
+    func_txt="Only including anatomical data [${BOLD_GREEN}${input_dir}${RESET}]"
     check_and_copy_anat \
       "${func_dir}" \
       "${base_path}" \
@@ -491,16 +524,23 @@ for subID in ${search}; do
   else
     #-----------------------------------------------------------------------------
     # include func
-    func_txt="Including functional data"
+    if [[ -z "${func_dir}" ]]; then
+      func_dir="${INPUT}"
+    else
+      INPUT="${func_dir}"
+    fi
+
+    input_dir="${func_dir}/${base_path}"
 
     # find func
-    func=$(
+    func=($(
       find_func_data \
       "${func_dir}" \
       "${base_path}" \
       "${input_dir}"
-    )
+    ))
 
+    func_txt="Including functional data [${#func[@]} files in ${BOLD_GREEN}${func_dir}${RESET}]"
     # anat still required
     check_and_copy_anat \
       "${func_dir}" \
@@ -511,9 +551,8 @@ for subID in ${search}; do
       "${base}" \
       "${DATA}"
 
-    if [[ -z "${func}" ]]; then
-      echo "${sub_name}; no \"*bold.nii.gz\" files in \"${input_dir}/func\""
-      echo "If you're running a multi-session setup with ses-1 (default) as anatomical session, specify a valid session ID using \"-n <sesID>\"."
+    if [[ -z "${func}" || ${#func[@]} -eq 0 ]]; then
+      print_file_not_in_dir "${sub_name}" "*bold.nii.gz" "${input_dir}/func" "Make sure the session ID (if applicable) is specified correctly and make sure to use \"-f <bids directory with BOLD data>\" to include functional data"
       continue
     fi
   fi
@@ -523,7 +562,7 @@ for subID in ${search}; do
   if [[ ${run_local} -eq 1 ]]; then
     # print header
     print_subject_header ${sub_name}
-    echo "${func_txt}"
+    echo -e "${func_txt}"
   fi
 
   #-----------------------------------------------------------------------------
@@ -535,6 +574,7 @@ for subID in ${search}; do
     "${remove_surf_wf}" \
     "${remove_wf}" \
     "${overwrite}" \
+    "${run_local}" \
     "${n_runs[@]}"
 
   #-----------------------------------------------------------------------------
@@ -561,31 +601,48 @@ for subID in ${search}; do
   # define the command
   cmd=(
     "${job}"
-    -s "${sub_id}"
-    -m "${mode}"
-    -b "${FPREP_BINDING}"
-    -r "${INPUT}"
-    -d "${OUTPUT}"
-    -w "${workdir}"
-    -c "${n_cpus}"
-    "${crash_flag}"
-    "${keep_runs}"
-    "${confFile}"
-    "${task_id}"
-    "${bbr_flag}"
-    "${kwargs_file}"
-    "${clean_wd}"
-    "${func_flag}"
-    "${anat_flag}"
-    "${docker_flag}"
+    -s "$sub_id"
+    -m "$mode"
+    -b "$FPREP_BINDING"
+    -r "$INPUT"
+    -d "$OUTPUT"
+    -w "$workdir"
+    -c "$n_cpus"
   )
+
+  [[ -n ${keep_runs:-} ]]   && cmd+=(-a "$keep_runs")
+  [[ -n ${task_id:-} ]]     && cmd+=(-t "$task_id")
+  [[ -n ${kwargs_file:-} ]] && cmd+=(-k "$kwargs_file")
+  [[ -n ${crash_flag:-} ]]  && cmd+=("$crash_flag")
+  [[ -n ${bbr_flag:-} ]]    && cmd+=("$bbr_flag")
+  [[ -n ${clean_wd:-} ]]    && cmd+=("$clean_wd")
+  [[ -n ${func_flag:-} ]]   && cmd+=("$func_flag")
+  [[ -n ${anat_flag:-} ]]   && cmd+=("$anat_flag")
+  [[ -n ${docker_flag:-} ]] && cmd+=("$docker_flag")
+  [[ -n ${dryrun_flag:-} ]] && cmd+=("$dryrun_flag") && echo -e "${BOLD_RED}DEBUG MODE ENABLED${RESET}" && echo
+
+  if [[ -n $confFile ]]; then
+    cmd+=(-y "$confFile")
+  fi
+
+  if [[ -n ${kwargs_flag:-} ]]; then
+      cmd+=(-x "$kwargs_flag")
+  fi
+
+  # clean up
+  clean_cmd=()
+  for arg in "${cmd[@]}"; do
+      [[ -n $arg ]] && clean_cmd+=("$arg")
+  done
+
+  cmd=("${clean_cmd[@]}")
 
   #-----------------------------------------------------------------------------
   # echo cmd
   if [[ ${run_local} -eq 1 ]]; then
     print_cmd "${cmd[@]}"
   fi
-
+  
   # run
   eval "${cmd[@]}"
   if [[ $? -ne 0 ]]; then
