docs/usage sync round 4

diff --git a/bin/call_fprepmask b/bin/call_fprepmask
--- a/bin/call_fprepmask
+++ b/bin/call_fprepmask
@@ -12,51 +12,92 @@ function Usage {
 ---------------------------------------------------------------------------------------------------
 call_fprepmask
 
-Apply the masks to the corresponding BOLD files given an fMRIprep directory. You can do something 
-similar with pybest, but this script exists in case you don't want to use that.
+Apply brain masks from fMRIPrep to their corresponding BOLD preprocessed images.
+
+This script multiplies each *_preproc_bold.nii.gz file with its corresponding brain_mask.nii.gz 
+file (usually found in the same directory). The resulting masked image is saved as 
+*masked_bold.nii.gz. This step is useful for excluding non-brain voxels prior to first-level 
+analysis or post-processing, especially if you're not using pybest or similar pipelines.
 
 Usage:
-  call_fprepmask <fprep dir>
+  call_fprepmask <fmriprep_directory>
 
-Example:
-  call_fprepmask # runs the script for all BOLD files in DIR_DATA_DERIV/fmriprep
-  call_fprepmask DIR_DATA_DERIV/fmriprep/sub-01 # runs the script for a single subject
-  call_fprepmask help # bring up this help 
-  
+Positional:
+  <fprep_dir>     Directory containing fMRIPrep outputs. This can be:
+                    - A full fMRIPrep derivatives folder (default: \$DIR_DATA_DERIV/fmriprep)
+                    - A single subject folder (e.g., .../fmriprep/sub-01)
+
+Options:
+  help|--help     print this help text
+
+Outputs:
+  For each *_preproc_bold.nii.gz file, a new file is created named:
+    *_masked_bold.nii.gz
+
+  The masking operation is performed using FSL's 'fslmaths' with the '-mas' flag.
+
+Examples:
+  call_fprepmask
+    → run masking for all BOLD files in \$DIR_DATA_DERIV/fmriprep
+
+  call_fprepmask /path/to/fmriprep/sub-01
+    → run masking for a single subject
+
+  call_fprepmask help
+    → show this help message
+
+Notes:
+  - This script assumes that the masks follow the BIDS-style naming convention and are
+    stored in the same directory as the corresponding preprocessed BOLD images.
+  - It will skip files for which no brain mask is found and print a warning.
+
 ---------------------------------------------------------------------------------------------------
 
 USAGE
-
 }
 
-# set default
+#-----------------------------------------------------------------------------
+# set path
 if [[ ${#@} -eq 0 ]]; then
   fprep_dir=${DIR_DATA_DERIV}/fmriprep
 else
   fprep_dir=${1}
   if [[ ${fprep_dir} == "help" || ${fprep_dir} == "--help" ]]; then
     Usage && exit 0
+  else
+    fprep_dir=$(readlink -f "${fprep_dir}")
   fi
 fi
 
-funcs=($(find ${fprep_dir} -type f -name "*preproc_bold.nii.gz" | sort))
+#-----------------------------------------------------------------------------
+# find funcs
+funcs=(
+  $(
+    find "${fprep_dir}" \
+    -type f -name "*preproc_bold.nii.gz" | 
+    sort
+  )
+)
+
 if [ ${#funcs[@]} -eq 0 ]; then
   echo
   print_line -
-  print_error_msg "$(basename ${0})" "find" "Could not find files with \"*preproc_bold.nii.gz\" in \"${fprep_dir}\""
+  print_error_msg "$(basename ${0})" "find" "Could not find files with \"*preproc_bold.nii.gz\" in ${BOLD_GREEN}${fprep_dir}${RESET}"
   exit 1
 fi
 
+#-----------------------------------------------------------------------------
+# loop through funcs
 echo "Input directory = \"${fprep_dir}\" (${#funcs[@]} files)"
 ct=1
 for f in ${funcs[@]}; do
-  base_name=$(dirname ${f})/$(basename ${f} preproc_bold.nii.gz)
-  mask_file=${base_name}brain_mask.nii.gz
-  if [ -f ${mask_file} ]; then
+  base_name="$(dirname ${f})/$(basename ${f} preproc_bold.nii.gz)"
+  mask_file="${base_name}brain_mask.nii.gz"
+  if [[ -f "${mask_file}" ]]; then
     echo -e "(${ct}/${#funcs[@]}): processing ${BOLD_GREEN}${f}${RESET}"
     
     # define output
-    out=${base_name}masked_bold.nii.gz
+    out="${base_name}masked_bold.nii.gz"
     
     # define command
     cmd=(
@@ -65,17 +106,18 @@ for f in ${funcs[@]}; do
       -mas "${mask_file}"
       "${out}"
     )
-    eval "${cmd[@]}"
 
-    if [ $? -ne 0 ]; then
+    # run
+    eval "${cmd[@]}"
+    if [[ $? -ne 0 ]]; then
       echo
       print_line -
-      print_error_msg "$(basename ${0})" "fslmaths"
+      print_error_msg "$(basename ${0})" "fslmaths" 
       exit 1
     else
       ((ct++))
     fi
   else
-    echo "mask file (\"${mask_file}\") does not exist"
+    echo "mask file (\"${mask_file}\") does not exist" "Failed with command: \"${cmd[@]}\""
   fi
 done
diff --git a/bin/call_fslepireg b/bin/call_fslepireg
--- a/bin/call_fslepireg
+++ b/bin/call_fslepireg
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 
 #-----------------------------------------------------------------------------
+# Get bash helper functions
+source call_bashhelper
+
+#-----------------------------------------------------------------------------
 # Create help text
 function Usage {
     cat <<USAGE
@@ -27,26 +31,29 @@ then run this script. You can specify to use FreeSurfer using the '-s <subject>'
 take SUBJECTS_DIR/<subject>/mri as default folder.
 
 Usage:
-    call_fslepireg [arguments] <epi_file> <output file>
+  call_fslepireg [arguments] <epi_file> <output file>
 
 Arguments:
-    <-s subject>    subject ID as specified in FreeSurfer directory if you want to use the FreeSur-
-                    fer as default inputs
-    <-t matrix>     specify a transformation matrix in case we want to warp the input files to a 
-                    different space first. As said above, it's better to get the BOLD in the desig-
-                    nated space first (e.g., with ITK-Snap), then run this script.
-    <-w wm file>    white matter segmentation if <subject> is empty
-    <-h t1head>     whole head T1w-image
-    <-b t1brain>    brain extracted T1w-image
-    <-i initial>    initial transformation to be applied to the BOLD file before registration. Can 
-                    be useful in combination with the <-s subject> (FreeSurfer) option. This should
-                    be a matrix created by manually placing the BOLD file over the t1brain/head.
-    <-q>            print this help
-    <-a>            convert output matrix to ANTs format
+  <-s subject>    subject ID as specified in FreeSurfer directory if you want to use the FreeSur-
+                  fer as default inputs
+  <-t matrix>     specify a transformation matrix in case we want to warp the input files to a 
+                  different space first. As said above, it's better to get the BOLD in the desig-
+                  nated space first (e.g., with ITK-Snap), then run this script.
+  <-w wm file>    white matter segmentation if <subject> is empty
+  <-h t1head>     whole head T1w-image
+  <-b t1brain>    brain extracted T1w-image
+  <-i initial>    initial transformation to be applied to the BOLD file before registration. Can 
+                  be useful in combination with the <-s subject> (FreeSurfer) option. This should
+                  be a matrix created by manually placing the BOLD file over the t1brain/head.
+  <-q>            print this help
+  <-a>            convert output matrix to ANTs format
+
+Options:
+  -q|--help       print this help text
 
 Positional:
-    <epi file>      input BOLD image
-    <output>        output file name
+  <epi file>      input BOLD image
+  <output>        output file name
 
 Example:
   call_fslepireg -h wholehead_T1w.nii.gz -b brain_T1w.nii.gz bold.nii.gz bold_in_t1w.nii.gz
@@ -65,70 +72,109 @@ if [[ $# -lt 2 ]] ; then
 fi
 
 #-----------------------------------------------------------------------------
-# Souce some helper functions such as fetch_filepath
-source call_bashhelper
-if [[ $? -ne 0 ]]; then
-    echo -e "${BOLD_RED}ERROR${RESET} in master: call_bashhelper exited with non-zero status. Make sure to specify full paths!"
-fi
-
-#-----------------------------------------------------------------------------
 # Deal with arguments
-while getopts qas:t:w:h:b:i: arg
+while getopts :-:qas:t:w:h:b:i: arg
 do
-    case ${arg} in
-        s)  subject=${OPTARG}
-            ;;
-        t)  matrix_file=${OPTARG}
-            ;;
-        w)  wm_file=${OPTARG}
-            ;;
-        h)  t1head=${OPTARG}
-            ;;
-        i)  initial=${OPTARG}
-            ;;					
-        b)  t1brain=${OPTARG}
-            ;;                                                    
-    esac
+  case ${arg} in
+    -)
+      case "${OPTARG}" in
+        help)
+          Usage && exit 0
+          ;;
+        *)
+          Usage
+          print_error_msg "$(basename ${0})" "getopt" "Unknown option --${OPTARG}"
+          exit 1
+          ;;
+      esac
+      ;;   
+    q)  Usage && exit 0
+          ;;  
+    s)  subject=${OPTARG}
+        ;;
+    t)  matrix_file=${OPTARG}
+        ;;
+    w)  wm_file=${OPTARG}
+        ;;
+    h)  t1head=${OPTARG}
+        ;;
+    i)  initial=${OPTARG}
+        ;;					
+    b)  t1brain=${OPTARG}
+        ;;                                                    
+  esac
 done
 
-epi_file=${@:$OPTIND:1}
+#-----------------------------------------------------------------------------
+# define inputs
+tmp="${@:$OPTIND:1}"
+if [[ ! -f "${tmp}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" "input" "Input file ${BOLD_GREEN}${tmp}${RESET} does not exist"
+  exit 1
+else
+  epi_file=$(readlink -f "${tmp}")
+fi
+
+# set output
 out_file=${@:$OPTIND+1:1}
 
 #-----------------------------------------------------------------------------
 # Check if we have FreeSurfer flag
 if [[ ! -z ${subject} ]]; then
 
-    if [[ -z ${SUBJECTS_DIR} ]];	then
-        echo -e "${BOLD_RED}ERROR${RESET} in $(basename ${0}): FreeSurfer was requested, but SUBJECTS_DIR is not set"
+  if [[ -z ${SUBJECTS_DIR} ]];	then
+    echo -e "${BOLD_RED}ERROR${RESET} in $(basename ${0}): FreeSurfer was requested, but SUBJECTS_DIR is not set"
+    exit 1
+  fi
+
+  wm_file=${SUBJECTS_DIR}/${subject}/mri/wm.nii.gz
+  t1head=${SUBJECTS_DIR}/${subject}/mri/orig.nii.gz
+  t1brain=${SUBJECTS_DIR}/${subject}/mri/brainmask.nii.gz
+  
+  # convert them to nifti for safety
+  for ii in ${wm_file} ${t1head} ${t1brain}; do
+    if [[ ! -f ${ii} ]]; then
+      
+      cmd=(
+        call_mriconvert
+        "$(dirname ${ii})/$(basename ${ii} .nii.gz).mgz"
+      )
+
+      # print and run
+      print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+      if [[ $? -ne 0 ]]; then
+        print_error_msg "$(basename ${0})" "call_mriconvert"
         exit 1
+      fi  
     fi
+  done
 
-    wm_file=${SUBJECTS_DIR}/${subject}/mri/wm.nii.gz
-    t1head=${SUBJECTS_DIR}/${subject}/mri/orig.nii.gz
-    t1brain=${SUBJECTS_DIR}/${subject}/mri/brainmask.nii.gz
-    
-    # convert them to nifti for safety
-    for ii in ${wm_file} ${t1head} ${t1brain}; do
-        if [[ ! -f ${ii} ]]; then
-            call_mriconvert $(dirname ${ii})/$(basename ${ii} .nii.gz).mgz
-            if [[ $? -ne 0 ]]; then
-                print_error_msg "$(basename ${0})" "call_mriconvert"
-                exit 1
-            fi  
-        fi
-    done
+  # binarize wm file, otherwise BBR will complain
+  cmd=(
+    fslmaths
+    "${wm_file}"
+    -bin 
+    "${wm_file}"
+  )
 
-    # binarize wm file, otherwise BBR will complain
-    fslmaths ${wm_file} -bin ${wm_file}
-
+  # print and run
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "fslmaths"
+    exit 1
+  fi
 fi
 
 #-----------------------------------------------------------------------------
 # check if we got a white matter file
 if [[ -z ${wm_file} ]]; then
-    do_we_have_wm=0
+  do_we_have_wm=0
 else
-    do_we_have_wm=1
+  do_we_have_wm=1
 fi
 
 #-----------------------------------------------------------------------------
@@ -138,162 +184,170 @@ out_file=${out_file}
 
 if [[ ! -z ${matrix_file} ]]; then
 
-    matrix_file=$(fetch_filepath ${matrix_file})
+  matrix_file=$(fetch_filepath ${matrix_file})
 
-    # by setting the reference and moving to the same image, we retain the geometry of the input files
-    # for the mask image (wm), we use a GenericLabel interpolation, for the T1w-images a linear
+  # by setting the reference and moving to the same image, we retain the geometry of the input files
+  # for the mask image (wm), we use a GenericLabel interpolation, for the T1w-images a linear
 
-    if [[ ${do_we_have_wm} -eq 1 ]]; then
-        cmd=(
-            call_antsapplytransforms
-            --gen
-            "${wm_file}"
-            "${wm_file}"
-            "$(dirname ${out_file})/wm_$(basename $out_file)"
-            "${matrix_file}"
-        )
-
-        print_cmd "${cmd[@]}" && eval "${cmd[@]}"
-        if [[ $? -ne 0 ]]; then
-            echo
-            print_line -
-            print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"wm\"-file"
-            exit 1
-        fi        
-
-        wm_file=$(dirname ${out_file})/wm_$(basename $out_file)
-        wm_flag="--wmseg=${wm_file}"
-    fi
-
+  if [[ ${do_we_have_wm} -eq 1 ]]; then
     cmd=(
-        call_antsapplytransforms
-        --lin
-        "${t1head}"
-        "${t1head}"
-        "$(dirname ${out_file})/t1head_$(basename $out_file)"
-        "${matrix_file}"
+      call_antsapplytransforms
+      --gen
+      "${wm_file}"
+      "${wm_file}"
+      "$(dirname ${out_file})/wm_$(basename $out_file)"
+      "${matrix_file}"
     )
 
+    # print and run
     print_cmd "${cmd[@]}" && eval "${cmd[@]}"
     if [[ $? -ne 0 ]]; then
-        echo
-        print_line -
-        print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"t1head\"-file"
-        exit 1
-    fi
+      echo
+      print_line -
+      print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"wm\"-file"
+      exit 1
+    fi        
 
-    cmd=(
-        call_antsapplytransforms
-        --lin
-        "${wm_file}"
-        "${wm_file}"
-        "$(dirname ${out_file})/t1brain_$(basename $out_file)"
-        "${matrix_file}"
-    )
+    wm_file=$(dirname ${out_file})/wm_$(basename $out_file)
+    wm_flag="--wmseg=${wm_file}"
+  fi
 
-    print_cmd "${cmd[@]}" && eval "${cmd[@]}"
-    if [[ $? -ne 0 ]]; then
-        echo
-        print_line -
-        print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"t1brain\"-file"
-        exit 1
-    fi
+  cmd=(
+    call_antsapplytransforms
+    --lin
+    "${t1head}"
+    "${t1head}"
+    "$(dirname ${out_file})/t1head_$(basename $out_file)"
+    "${matrix_file}"
+  )
 
-    # overwrite variables; we need to do that after call_antsapplytransforms otherwise bad things happen
-    t1head=$(dirname ${out_file})/t1head_$(basename $out_file)
-    t1brain=$(dirname ${out_file})/t1brain_$(basename $out_file)
+  # print and run
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"t1head\"-file"
+    exit 1
+  fi
+
+  cmd=(
+    call_antsapplytransforms
+    --lin
+    "${wm_file}"
+    "${wm_file}"
+    "$(dirname ${out_file})/t1brain_$(basename $out_file)"
+    "${matrix_file}"
+  )
+
+  # print and run
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"t1brain\"-file"
+    exit 1
+  fi
+
+  # overwrite variables; we need to do that after call_antsapplytransforms otherwise bad things happen
+  t1head=$(dirname ${out_file})/t1head_$(basename $out_file)
+  t1brain=$(dirname ${out_file})/t1brain_$(basename $out_file)
 
 else
-    if [[ ${do_we_have_wm} -eq 1 ]]; then
-        wm_flag="--wmseg=${wm_file}"
-    else
-        wm_flag=""
-    fi
+  if [[ ${do_we_have_wm} -eq 1 ]]; then
+    wm_flag="--wmseg=${wm_file}"
+  else
+    wm_flag=""
+  fi
 fi
 
 #-----------------------------------------------------------------------------
 # Check if we should warp functional stuff
 if [[ ! -z ${initial} ]]; then
-    initial=$(fetch_filepath ${initial})
-    cmd=(
-        call_antsapplytransforms
-        --lin
-        "${t1head}"
-        "${epi_file}"
-        "$(dirname ${out_file})/bold_in_t1head.nii.gz"
-        "${initial}"
-    )
+  initial=$(fetch_filepath ${initial})
+  cmd=(
+    call_antsapplytransforms
+    --lin
+    "${t1head}"
+    "${epi_file}"
+    "$(dirname ${out_file})/bold_in_t1head.nii.gz"
+    "${initial}"
+  )
 
-    print_cmd "${cmd[@]}" && eval "${cmd[@]}"
-    if [[ $? -ne 0 ]]; then
-        echo
-        print_line -
-        print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"initial\"-file"
-        exit 1
-    fi
+  # print and run
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Stage=\"initial\"-file"
+    exit 1
+  fi
 
-    epi_file=$(dirname ${out_file})/bold_in_t1head.nii.gz
+  epi_file=$(dirname ${out_file})/bold_in_t1head.nii.gz
 fi
 
 #-----------------------------------------------------------------------------
 # Run the epi_reg command
 if [[ -f ${t1head} && -f ${t1brain} ]]; then
-    cmd=(
-        epi_reg
-        --epi="${epi_file}"
-        --t1="${t1head}"
-        --t1brain="${t1brain}"
-        --out="${out_file}"
-        "${wm_flag}"
-    )
+  cmd=(
+    epi_reg
+    --epi="${epi_file}"
+    --t1="${t1head}"
+    --t1brain="${t1brain}"
+    --out="${out_file}"
+    "${wm_flag}"
+  )
 
-    print_cmd "${cmd[@]}" && eval "${cmd[@]}"
-    if [[ $? -ne 0 ]]; then
-        echo
-        print_line -
-        print_error_msg "$(basename ${0})" "epi_reg"
-        exit 1
-    fi
-
-else
-    echo -e "${BOLD_RED}ERROR${RESET} in $(basename ${0}): could not find t1brain/t1head-files"
+  # print and run
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "epi_reg"
     exit 1
+  fi
+else
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" "call_antsapplytransforms" "Could not find t1brain/t1head-files"
+  exit 1
 fi
 
 #-----------------------------------------------------------------------------
 # Check if we should convert the matrix to ANTs format
 if [[ "${@}" == *"-a"* ]]; then
-    fname=$(dirname ${out_file})/$(basename ${out_file} .nii.gz)
-    cmd=(
-        call_ras2fsl
-        -i
-        "${t1head}"
-        "${epi_file}"
-        "${fname}.mat"
-        "${fname}.txt"
-    )
+  fname=$(dirname ${out_file})/$(basename ${out_file} .nii.gz)
+  cmd=(
+    call_ras2fsl
+    -i
+    "${t1head}"
+    "${epi_file}"
+    "${fname}.mat"
+    "${fname}.txt"
+  )
 
-    print_cmd "${cmd[@]}" && eval "${cmd[@]}"
-    if [[ $? -ne 0 ]]; then
-        echo
-        print_line -
-        print_error_msg "$(basename ${0})" "call_ras2fsl"
-        exit 1
-    fi
+  # print and run
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "call_ras2fsl"
+    exit 1
+  fi
 
-    cmd=(
-        ConvertTransformFile
-        3
-        "${fname}.txt"
-        "${fname}_itk.mat"
-        --convertToAffineType
-    )
+  cmd=(
+    ConvertTransformFile
+    3
+    "${fname}.txt"
+    "${fname}_itk.mat"
+    --convertToAffineType
+  )
 
-    print_cmd "${cmd[@]}" && eval "${cmd[@]}"
-    if [[ $? -ne 0 ]]; then
-        echo
-        print_line -
-        print_error_msg "$(basename ${0})" "ConvertTransformFile"
-        exit 1
-    fi
+  # print and run
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "ConvertTransformFile"
+    exit 1
+  fi
 fi
