double quotes

diff --git a/bin/call_vol2vol b/bin/call_vol2vol
--- a/bin/call_vol2vol
+++ b/bin/call_vol2vol
@@ -39,17 +39,22 @@ if [[ -f $1 && -f $2 ]]; then
 
   if [[ ! -f $3 ]]; then
 
-    CMD=`command -v mri_vol2vol`
-    if [[ ! -z $CMD ]]; then
-      $CMD --mov $1 --targ $2 --regheader --o $3 --save-reg
+    CMD=$(command -v mri_vol2vol)
+    if [[ ! -z "${CMD}" ]]; then
+      "${CMD}" \
+        --mov "${1}" \
+        --targ "${2}" \
+        --regheader \
+        --o "${3}" \
+        --save-reg
     else
       echo "mri_vol2vol is not on your path.. Make sure FreeSurfer is added to your path"
       exit 1
     fi
+  else
+    echo "Output exists, won't overwrite"
   fi
-
 else
-
-  echo "Output exists, won't overwrite"
-
+  echo "Missing SOURCE and TARGET images"
+  exit 1
 fi
