double quotes

diff --git a/bin/call_antsregistration b/bin/call_antsregistration
--- a/bin/call_antsregistration
+++ b/bin/call_antsregistration
@@ -261,9 +261,11 @@ do
   esac
 done
 
+#-----------------------------------------------------------------------------
 # set number of cores to use
 export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=${n_cpu}
 
+#-----------------------------------------------------------------------------
 # function to derive the convergence, smoothing, shrinking parameters.
 function check_stage_inputs {
   
@@ -314,9 +316,10 @@ function check_stage_inputs {
   echo ${par}
 }
 
+#-----------------------------------------------------------------------------
 function validate_extension {
 
-  in_file=${1}
+  in_file="${1}"
   ext_file=$(fetch_extension "${in_file}")
   if [[ ${ext_file} == "gz" ]] || [[ ${ext_file} == "nii" ]]; then
     :
@@ -330,18 +333,22 @@ function validate_extension {
         exit 1
       fi  
 
-      in_file=$(dirname ${in_file})/$(basename ${in_file} .${ext_file}).nii.gz
+      in_file="${in_file/.${ext_file}/.nii.gz}"
     else
-      echo -e "${BOLD_RED}ERROR${RESET} in $(basename ${0}); Input must be a nii(.gz) or .mgz file, not \"${ext_file}\""
+      echo
+      print_line -
+      print_error_msg "$(basename ${0})" "input" "Input must be a nii(.gz) or .mgz file, not \"${ext_file}\""
       exit 1
     fi
   fi
 
-  echo ${in_file}
+  echo "${in_file}"
 }
 
-# check if we got custom inputs, whether we should use defaults, and whether specified values match the number of levels specified
-# if check_stage_inputs fails, the returned value will be the error message, so we can conveniently make a traceback
+#-----------------------------------------------------------------------------
+# check if we got custom inputs, whether we should use defaults, and whether specified values 
+# match the number of levels specified if check_stage_inputs fails, the returned value will be the 
+# error message, so we can conveniently make a traceback
 shrink=$(check_stage_inputs shrink)
 if [[ $? -ne 0 ]]; then
   echo
@@ -370,11 +377,15 @@ if [[ $# -lt 3 ]] ; then
   Usage && exit 0
 fi
 
+#-----------------------------------------------------------------------------
+# read args
 REF=${@:$OPTIND:1}
 MOV=${@:$OPTIND+1:1}
 OUT=${@:$OPTIND+2:1}
 
-if [[ ! -f ${REF} ]]; then
+#-----------------------------------------------------------------------------
+# check inputs
+if [[ ! -f "${REF}" ]]; then
   echo
   print_line -
   print_error_msg "$(basename ${0})" "find" "Could not find FIXED image \"${BOLD_GREEN}${REF}${RESET}\""
@@ -383,7 +394,7 @@ else
   REF=$(readlink "${REF}")
 fi
 
-if [[ ! -f ${MOV} ]]; then
+if [[ ! -f "${MOV}" ]]; then
   echo
   print_line -
   print_error_msg "$(basename ${0})" "find" "Could not find MOVING image \"${BOLD_GREEN}${MOV}${RESET}\""
@@ -391,6 +402,13 @@ if [[ ! -f ${MOV} ]]; then
 else
   MOV=$(readlink -f "${MOV}")
 fi  
+
+if [[ -z "${OUT}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify output file"
+  exit 1
+fi
 
 #-----------------------------------------------------------------------------
 # set flag to extract first volume from 4D image to 0
@@ -402,7 +420,7 @@ extract_moving=0
 # extensions and dimensionality
 
 # check extension
-REF=$(validate_extension ${REF})
+REF=$(validate_extension "${REF}")
 if [[ $? -ne 0 ]]; then
   echo
   print_line -
@@ -410,7 +428,7 @@ if [[ $? -ne 0 ]]; then
   exit 1
 fi
 
-MOV=$(validate_extension ${MOV})
+MOV=$(validate_extension "${MOV}")
 if [[ $? -ne 0 ]]; then
   echo
   print_line -
@@ -419,8 +437,8 @@ if [[ $? -ne 0 ]]; then
 fi
 
 # check dimensions
-DIMfixed=$(fslval ${REF} dim0)
-DIMmoving=$(fslval ${MOV} dim0)
+DIMfixed=$(fslval "${REF}" dim0)
+DIMmoving=$(fslval "${MOV}" dim0)
 if [[ $DIMfixed != $DIMmoving ]]; then
 
   # check if we can extract first volume of time-series
@@ -430,13 +448,27 @@ if [[ $DIMfixed != $DIMmoving ]]; then
       echo "Taking first volume of 4D-moving image"
     fi
     
-    MOVING=$(dirname ${MOV})/example_moving.nii.gz
-    fslroi ${MOV} ${MOVING} 0 1
     extract_moving=1
+    MOVING="$(dirname ${MOV})/example_moving.nii.gz"
+    cmd=(
+      fslroi
+      "${MOV}"
+      "${MOVING}"
+      0
+      1
+    )
 
+    # print and run
+    print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+    if [[ $? -ne 0 ]]; then
+      echo
+      print_line -
+      print_error_msg "$(basename ${0})" "${cmd[0]}"
+      exit 1
+    fi
   else  
-    DIM=$DIMmoving
-    MOVING=${MOV}
+    DIM="${DIMmoving}"
+    MOVING="${MOV}"
   fi
 
   if [[ $((${DIMfixed})) -eq 4 ]]; then
@@ -445,12 +477,26 @@ if [[ $DIMfixed != $DIMmoving ]]; then
       echo "Taking first volume of 4D-fixed image"
     fi
     
-    FIXED=$(dirname ${REF})/example_fixed.nii.gz
-    fslroi ${REF} ${FIXED} 0 1
     extract_fixed=1
+    FIXED="$(dirname ${REF})/example_fixed.nii.gz"
+    cmd=(
+      fslroi
+      "${REF}"
+      "${FIXED}"
+      0
+      1
+    )
+    # print and run
+    print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+    if [[ $? -ne 0 ]]; then
+      echo
+      print_line -
+      print_error_msg "$(basename ${0})" "${cmd[0]}"
+      exit 1
+    fi
   else  
-    DIM=$DIMmoving
-    FIXED=${REF}
+    DIM="${DIMmoving}"
+    FIXED="${REF}"
   fi
 
   # final check
@@ -462,19 +508,19 @@ if [[ $DIMfixed != $DIMmoving ]]; then
   fi
 
 else
-  FIXED=${REF}
-  MOVING=${MOV}
+  FIXED="${REF}"
+  MOVING="${MOV}"
 fi
 
 #-----------------------------------------------------------------------------
 # Deal with initial transform file if the argument is not empty.
-if [[ ! -z ${initial} ]]; then
+if [[ ! -z "${initial}" ]]; then
 
   if [ ${VERB} -eq 1 ]; then
     echo "Using $(basename ${initial}) as initial moving transform file"
   fi
   
-  ext=$(fetch_extension ${initial})
+  ext=$(fetch_extension "${initial}")
   if [[ $ext != "txt" ]]; then
     print_error_msg "$(basename ${0})" "ext" "\"${initial}\" is not a text file. It should be if it's an initial moving transform file"
     exit 1
@@ -482,12 +528,11 @@ if [[ ! -z ${initial} ]]; then
     # If we have an initial moving transform matrix, insert this line in the command
     INITIAL=$(echo "-r ${initial}")
   fi
-
 fi
 
 #-----------------------------------------------------------------------------
 # Deal with mask file if the argument is not empty.
-if [[ ! -z ${mask} ]]; then
+if [[ ! -z "${mask}" ]]; then
   if [ ${VERB} -eq 1 ]; then
     echo "Using $(basename ${mask}) as mask file"
   fi
@@ -581,11 +626,9 @@ if [[ ${VERB} -eq 1 ]]; then
 fi
 
 # echo command to text file
-cmd_f=${OUT}command.txt
-if [ -f ${cmd_f} ]; then
-  rm ${cmd_f} 2>/dev/null
-fi
-echo "${cmd}" >> ${OUT}command.txt
+cmd_f="${OUT}command.txt"
+rm ${cmd_f} 2>/dev/null
+echo "${cmd}" >> "${cmd_f}"
 
 # Execute command
 eval "${cmd}"
@@ -597,13 +640,13 @@ if [[ $? -ne 0 ]]; then
 fi
 
 # rename
-if [[ -f ${OUT}0GenericAffine.mat ]]; then
+if [[ -f "${OUT}0GenericAffine.mat" ]]; then
   input_for_c3d="${OUT}genaff.mat"
   mv "${OUT}0GenericAffine.mat" "${input_for_c3d}" 2>/dev/null
 fi
 
 # this file is created if --collapse-output-transforms is set to 0 and you did rigid-body registration; safest bet is to keep --collapse-output-transforms to 1 so you always get the same output 
-if [[ -f ${OUT}0Rigid.mat ]]; then
+if [[ -f "${OUT}0Rigid.mat" ]]; then
   input_for_c3d="${OUT}rigid.mat"
   mv "${OUT}0Rigid.mat" "${input_for_c3d}" 2>/dev/null
 fi
@@ -636,11 +679,11 @@ fi
 
 # remove temporary file
 if [[ ${extract_moving} -eq 1 ]]; then
-  rm ${MOVING} 2>/dev/null
+  rm "${MOVING}" 2>/dev/null
 fi
 
 if [[ ${extract_fixed} -eq 1 ]]; then
-  rm ${FIXED} 2>/dev/null
+  rm "${FIXED}" 2>/dev/null
 fi
 
 # open ITK-Snap for verification
@@ -651,7 +694,7 @@ if [[ ${open_itk} -eq 1 ]]; then
     -g "${FIXED}"
     -o "${MOVING}"
   )
-  print_cmd "${cmd[@]}" && "${cmd[@]}"
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
 fi
 
 # reset threads
diff --git a/bin/call_calculatemean b/bin/call_calculatemean
--- a/bin/call_calculatemean
+++ b/bin/call_calculatemean
@@ -49,45 +49,69 @@ fi
 output=${@: -1}
 inputs=${@:1:$#-1}
 
+#-----------------------------------------------------------------------------
 # Function for merge command
-COMMAND() {
-  fslmerge -a $(dirname "$1")/tmp_$(basename "$1") "${@:2}"
-}
-
-# Only proceed if output doesn't exist
-if [[ ! -f ${output} ]]; then
-
-  # If temporary file doesn't exist, run merge
-  if [[ ! -f $(dirname "${output}")/tmp_$(basename "${output}") ]]; then
-
-    echo "Merging the following files:"
-    for i in ${inputs[@]}; do echo "  $(basename "$i")"; done
-
-    COMMAND "${output}" "${inputs[@]}"
-
-    if [[ $? -ne 0 ]]; then
-      echo
-      print_line -
-      print_error_msg "$(basename "$0")" "fslmerge"
-      exit 1
-    fi
-  fi
-
-  echo "Calculating mean"
+merge_files() {
+  local output="${1}"
+  local inputs="${@:2}"
   cmd=(
-    fslmaths
-    "$(dirname "${output}")/tmp_$(basename "${output}")"
-    -Tmean
+    fslmerge
+    -a
     "${output}"
+    "${inputs[@]}"
   )
-
+  
   print_cmd "${cmd[@]}" && eval "${cmd[@]}"
   if [[ $? -ne 0 ]]; then
     echo
     print_line -
-    print_error_msg "$(basename "$0")" "fslmaths"
+    print_error_msg "$(basename "$0")" "${cmd[0]}"
     exit 1
   fi
+}
 
-  rm "$(dirname "${output}")/tmp_$(basename "${output}")" 2>/dev/null
+#-----------------------------------------------------------------------------
+# If temporary file doesn't exist, run merge
+tmp_file="${output%/*}/tmp_${output##*/}"
+if [[ ! -f "${tmp_file}" ]]; then
+
+  echo "Merging the following files:"
+  for i in ${inputs[@]}; do echo "  $(basename "${i}")"; done
+
+  cmd=(
+    merge_files
+    "${tmp_file}"
+    "${inputs[@]}"
+  )
+  
+  print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+  if [[ $? -ne 0 ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename "$0")" "${cmd[0]}"
+    exit 1
+  fi
 fi
+
+#-----------------------------------------------------------------------------
+# calculate mean
+echo "Calculating mean"
+cmd=(
+  fslmaths
+  "${tmp_file}"
+  -Tmean
+  "${output}"
+)
+
+# print and run
+print_cmd "${cmd[@]}" && eval "${cmd[@]}"
+if [[ $? -ne 0 ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename "$0")" "fslmaths"
+  exit 1
+fi
+
+#-----------------------------------------------------------------------------
+# clean up
+rm "${tmp_file}" 2>/dev/null
diff --git a/bin/call_cat12 b/bin/call_cat12
--- a/bin/call_cat12
+++ b/bin/call_cat12
@@ -31,7 +31,7 @@ Positional:
   <input image>   input image. Can either be *.nii.gz or *.nii image. In the case of the former,
                   new *.nii-file will be created alongside of the *.nii.gz file, as SPM does
                   not like *.nii.gz files.
-  <output path>	path to output directory; in here, 'mri' and 'report' will be stored
+  <output path>	  path to output directory; in here, 'mri' and 'report' will be stored
 
 Example:
   call_cat12 /path/to/inputfile.nii.gz /path/to/output_dir
@@ -78,20 +78,53 @@ do
   esac
 done
 
-INPUT=${@:$OPTIND:1}
-OUTPUT=${@:$OPTIND+1:1}
+#-----------------------------------------------------------------------------
+# read args
+in_file=${@:$OPTIND:1}
+out_dir=${@:$OPTIND+1:1}
+
+#-----------------------------------------------------------------------------
+# check inputs
+if [[ ! -f "${in_file}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Could not find input image \"${BOLD_GREEN}${in_file}${RESET}\""
+  exit 1
+else
+  in_file=$(readlink -f "${in_file}")
+fi
+
+# set input dir
+in_dir="$(dirname "${in_file}")"
+
+if [[ -z "${out_file}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify output directory"
+  exit 1
+fi
 
 #-----------------------------------------------------------------------------
 # Define default SPM-path
 if [[ -z "${SPM}" ]]; then
   if [[ -z "${SPM_PATH}" ]]; then
-    echo "ERROR: SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "SPM" "SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
     exit 1
   else
     SPM_PATH="${SPM_PATH}"
   fi
 else
   SPM_PATH="${SPM}"
+fi
+
+# double check if directory exists
+if [[ ! -d "${SPM_PATH}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" "SPM" "Could not find SPM directory ${BOLD_GREEN}${SPM_PATH}${RESET}"
+  exit 1
 fi
 
 #-----------------------------------------------------------------------------
@@ -107,21 +140,20 @@ else
   fi
 fi
 
-# if file specified is in current directory, add entire path
-INPUT=$(fetch_filepath "${INPUT}")
-
-ext=$(fetch_extension "${INPUT}")
+#-----------------------------------------------------------------------------
+# check if input is nii or nii.gz
+ext=$(fetch_extension "${in_file}")
 if [[ ${ext} == "gz" ]]; then
-  in_file=$(dirname "${INPUT}")/$(basename "${INPUT}" .gz)
-  gunzip -c "${INPUT}" > "${in_file}"
+  tmp_file="${in_file/.nii.gz/.nii}"
+  gunzip -c "${in_file}" > "${tmp_file}"
 else
-  in_file="${INPUT}"
+  tmp_file="${in_file}"
 fi
 
 #-----------------------------------------------------------------------------
 # Define default LOG-path
 if [[ -z ${LOG} ]]; then
-  LOG_DIR="$(dirname "${in_file}")"
+  LOG_DIR="${in_dir}"
 else
   LOG_DIR="${LOG}"
 fi
@@ -137,26 +169,27 @@ if [[ -f "${new_script}" ]]; then
   rm -r "${new_script}"
 fi
 
-if [[ ! -d ${OUTPUT} ]]; then
-  mkdir -p ${OUTPUT}
+if [[ ! -d "${out_dir}" ]]; then
+  mkdir -p "${out_dir}"
 fi
 
+#-----------------------------------------------------------------------------
 # Only run stuff if we can't find 'mri'-directory in the directory from the input
 # file or in the specified output-directory. Mind you, it therefore does NOT over-
 # write stuff from CAT12..
-if [[ -d "${OUTPUT}/mri" ]]; then
-  if [[ $(ls "${OUTPUT}/mri" | wc -l) -eq 0 ]]; then
+if [[ -d "${out_dir}/mri" ]]; then
+  if [[ $(ls "${out_dir}/mri" | wc -l) -eq 0 ]]; then
     RUN=1
     verdict="Running CAT12:"
-    reason="${OUTPUT}/mri is empty"
+    reason="${out_dir}/mri is empty"
   else
     verdict="Not running CAT12:"
-    reason="${OUTPUT}/mri is not empty"  
+    reason="${out_dir}/mri is not empty"  
     RUN=0
   fi
 else
-  if [[ -d $(dirname "${in_file}")/mri ]]; then
-    if [[ $(ls $(dirname "${in_file}")/mri | wc -l) -eq 0 ]]; then
+  if [[ -d "${in_dir}/mri" ]]; then
+    if [[ $(ls "${in_dir}/mri" | wc -l) -eq 0 ]]; then
       RUN=1
       verdict="Running CAT12"
       reason="input folder contains empty \"mri\"-folder"
@@ -167,12 +200,12 @@ else
     fi
   else
     # some CAT versions might not have mri/ report/ folders
-    if ls "${OUTPUT}"/p[0-4]sub* &>/dev/null; then
+    if ls "${out_dir}"/p[0-4]sub* &>/dev/null; then
       RUN=0
       verdict="Not running CAT12"
       reason="p[0-4]-files (probability maps) present in output folder"
     else
-      if ls "$(dirname "${in_file}")"/p[0-4]sub* &>/dev/null; then
+      if ls "${in_dir}"/p[0-4]sub* &>/dev/null; then
         RUN=0
         verdict="Not running CAT12"
         reason="input folder contains p[0-4]-files"
@@ -185,46 +218,55 @@ else
   fi
 fi
 
+#-----------------------------------------------------------------------------
+# run
 echo "${verdict}: ${reason}"
 if [[ ${RUN} -eq 1 ]]; then
 
+  #-----------------------------------------------------------------------------
   # make_cat_script = in call_bashhelper
-  make_cat_script "${SPM_PATH}" "${in_file}" ${MODE} "${new_script}"
+  make_cat_script \
+    "${SPM_PATH}" \
+    "${tmp_file}" \
+    "${MODE}" \
+    "${new_script}"
   
+  #-----------------------------------------------------------------------------
+  # store output in log file so we can check for errors
+  log_file="${out_dir}/catlog.txt"
+  rm -r "${log_file}" 2>/dev/null
+
+  #-----------------------------------------------------------------------------
   # call_matlab = in call_bashhelper
   echo "Starting CAT12.."
-
-  # store output in log file so we can check for errors
-  log_file="${OUTPUT}/catlog.txt"
-  if [ -f "${log_file}" ]; then
-    rm -r "${log_file}" 2>/dev/null
-  fi
-
   call_matlab "${new_script}" >> "${log_file}"
 
+  #-----------------------------------------------------------------------------
   # we should have p* files by now
-  ff=$(find "$(dirname "${in_file}")" -type f \( -name "p[0-4]sub*.nii" \))
-  if [[ -z ${ff} ]]; then
+  ff=$(find "${in_dir}" -type f \( -name "p[0-4]sub*.nii" \))
+  if [[ -z "${ff}" ]]; then
     echo 
     print_line -
     print_error_msg "$(basename ${0})" "CAT12:Segmentation" "Segmentation files not created"
     exit 1
   fi
 
+  #-----------------------------------------------------------------------------
   # check if matlab succeeded
   ff=$(cat "${log_file}" | grep "Failed: CAT12: Segmentation" | cut -d"." -f2 | xargs | sed 's/\r$//')
-  if [[ ! -z ${ff} ]]; then
-    mv "${log_file}" $(dirname "${in_file}")/$(basename "${in_file}" .nii)_error.log
+  if [[ ! -z "${ff}" ]]; then
+    mv "${log_file}" "${tmp_file/.nii/_error.log}" 2>/dev/null
     echo
     print_line -
     print_error_msg "$(basename ${0})" "matlab"
     exit 1
   else
-    mv "${log_file}" $(dirname "${in_file}")/$(basename "${in_file}" .nii).log
+    mv "${log_file}" "${tmp_file/.nii/.log}" 2>/dev/null
   fi
 
+  #-----------------------------------------------------------------------------
   # check for error-directory
-  if [[ -d $(dirname "${in_file}")/err ]]; then
+  if [[ -d "${in_dir}/err" ]]; then
     echo 
     print_line -
     print_error_msg "$(basename ${0})" "CAT12:Segmentation" "CAT12 encountered an error"
@@ -232,46 +274,59 @@ if [[ ${RUN} -eq 1 ]]; then
   fi
 fi
 
+#-----------------------------------------------------------------------------
 # Copy relevant files to OUTPUT
 echo "Finding and copying CAT12 log and report files..."
-find "$(dirname "${in_file}")" -type f \( -name "catlog*" -o -name "catreport*" -o -name "*.log" \) -print0 | while IFS= read -r -d '' file; do
-  mv "$file" "${OUTPUT}/"
+find "${in_dir}" -type f \( -name "catlog*" -o -name "catreport*" -o -name "*.log" \) -print0 | while IFS= read -r -d '' file; do
+  mv "${file}" "${out_dir}/"
 done
 
+#-----------------------------------------------------------------------------
+# compress output if needed
 echo "Finding and processing segmentation output files..."
-find "$(dirname "${in_file}")" -type f \( -name "p[0-4]sub*.nii" -o -name "msub*.nii" \) -print0 | sort -z | while IFS= read -r -d '' file; do
+find "${in_dir}" -type f \( -name "p[0-4]sub*.nii" -o -name "msub*.nii" \) -print0 | sort -z | while IFS= read -r -d '' file; do
   
   # copy file 
-  mv "$file" "${OUTPUT}/"
-  out_file="${OUTPUT}/$(basename "$file").gz"
+  mv "$file" "${out_dir}/"
+  out_file="${out_dir}/$(basename "$file").gz"
   if [[ ${ext} == "gz" ]]; then
     # compress
     echo -e " Compressing ${BOLD_GREEN}$(basename "$file")${RESET} to ${BOLD_RED}.nii.gz${RESET}"
-    gzip -f "${OUTPUT}/$(basename "$file")"
+    gzip -f "${out_dir}/$(basename "$file")"
   fi
 
   # copy geometry from input file
-  cmd="call_copyheader "${INPUT}" "${out_file}""
+  cmd=(
+    call_copyheader
+    "${in_file}"
+    "${out_file}"
+  )
   
   # run
-  eval "${cmd}"
+  eval "${cmd[@]}"
   if [[ $? -ne 0 ]]; then
     echo 
     print_line -
-    print_error_msg "$(basename ${0})" "call_copyheader"
+    print_error_msg "$(basename ${0})" "${cmd[0]}"
     exit 1
   fi
 done
 
+#-----------------------------------------------------------------------------
 # create binary mask from p0-segmentation (= brain extracted image)
-img_for_mask=$(find ${OUTPUT} -type f -name "p0*") 2>/dev/null
-if [ ! -z ${img_for_mask} ]; then
+img_for_mask=$(
+  find "${out_dir}" \
+  -type f \
+  -name "p0*"
+) 2>/dev/null
+
+if [ ! -z "${img_for_mask}" ]; then
   echo "Create mask from brain extracted segmentation image \"p0\""
   cmd=(
     fslmaths
     "${img_for_mask}"
     -bin
-    "${OUTPUT}/mask$(basename ${img_for_mask})"
+    "${out_dir}/mask$(basename ${img_for_mask})"
   )
 
   # run
@@ -284,12 +339,15 @@ if [ ! -z ${img_for_mask} ]; then
   fi
 fi
 
+#-----------------------------------------------------------------------------
 # clean up if folders exists (depending on version)
-find "$(dirname "${INPUT}")" -type f \( -name "*T1w.mat" -o -name "*T1w.xml" \) -exec rm {} \; 2>/dev/null
-rm -r "${OUTPUT}/mri" "${OUTPUT}/err" "${OUTPUT}/report" 2>/dev/null
-rm -r "$(dirname "${INPUT}")/mri" "$(dirname "${INPUT}")/err" "$(dirname "${INPUT}")/report" 2>/dev/null
+find "${in_dir}" -type f \( -name "*T1w.mat" -o -name "*T1w.xml" \) -exec rm {} \; 2>/dev/null
+
+for d in "${in_dir}" "${out_dir}"; do
+  rm -r "${d}/mri" "${d}/err" "${d}/report" 2>/dev/null
+done
 
 # remove created T1w.nii files
 if [[ ${ext} == "gz" ]]; then
-  rm -r "${in_file}" 2>/dev/null
+  rm -r "${tmp_file}" 2>/dev/null
 fi
diff --git a/bin/call_distance b/bin/call_distance
--- a/bin/call_distance
+++ b/bin/call_distance
@@ -95,9 +95,27 @@ if [[ $# -lt 1 ]]; then
   Usage && exit 0
 fi
 
+#-----------------------------------------------------------------------------
+# read args
 SUB=${@:$OPTIND:1}
 OUT=${@:$OPTIND+1:1}
 
+if [[ -z "${SUB}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify subject ID"
+  exit 1
+fi
+
+if [[ -z "${OUT}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify output file"
+  exit 1
+fi
+
+#-----------------------------------------------------------------------------
+# decide surface type
 if [[ ${fiducial} -eq 1 ]]; then
   SURF="fiducial"
 fi
@@ -110,6 +128,8 @@ if [[ ${pial} -eq 1 ]]; then
   SURF="pial"
 fi
 
+#-----------------------------------------------------------------------------
+# start
 start_timer "call_distance; distance estimation using Dykstra's algorithm"
 echo "sub   = ${SUB}"
 echo "surf  = ${SURF}"
@@ -119,6 +139,8 @@ echo "start = ${start_v}"
 echo "end   = ${end_v}"
 echo "out   = ${OUT}"
 
+#-----------------------------------------------------------------------------
+# clean up
 function clean {
   rm -r $PWD/M_weights_distance.mat 2>/dev/null
   rm -r $PWD/options.txt 2>/dev/null
@@ -128,6 +150,8 @@ function clean {
   rm -r $PWD/cost.txt 2>/dev/null
 }
 
+#-----------------------------------------------------------------------------
+# read vertices 
 function read_vertices {
   PYTHON_CODE=$(cat <<END
 from cxutils import optimal;
@@ -144,6 +168,8 @@ END
   echo $PYTHON_CODE
 }
 
+#-----------------------------------------------------------------------------
+# redo vertices
 function fill_vertices {
   PYTHON_CODE=$(cat <<END
 import json;
@@ -227,7 +253,7 @@ else
       done
     fi
     # iteratively fill vertices where process exited with non-zero status
-    fill_vertices ${OUT}
+    fill_vertices "${OUT}"
   fi 
 fi
 
diff --git a/bin/call_replace b/bin/call_replace
--- a/bin/call_replace
+++ b/bin/call_replace
@@ -1,6 +1,32 @@
 #!/usr/bin/env bash
 
 #-----------------------------------------------------------------------------
+# function to replace using perl
+function search_string {
+  local file="${1}"
+  local search="${2}"
+  local replace="${3}"
+
+  case $(grep -rn "${search}" ${file} >/dev/null; echo $?) in
+    0)
+    # code if found
+    if [[ ${verbose} -eq 1 ]]; then
+      echo "replacing \"${search}\" with \"${replace}\" in \"${file}\""
+    fi
+
+    perl -pi -e 's|'"${search}"'|'"${replace}"'|g' "${file}"
+    ;;
+    1)
+    # code if not found
+    ;;
+    *)
+    # code if an error occurred
+    echo "FAILURE: \"${file}\""
+    ;;
+  esac
+}
+
+#-----------------------------------------------------------------------------
 # Create help text
 function Usage {
     cat <<USAGE
@@ -18,7 +44,11 @@ Usage:
 Arguments:
   <search for>    string to be replaced
   <replace with>  replacement string
-  <dir/file>      directory or file to perform the operation on
+  <dir/file>      directory or file to perform the operation on if '--recursive' is not specified.
+                  If '--recursive' is passed, files in all subdirectories will also be considered.
+
+Optional:
+  -d <depth>      maximum search depth passed on to 'find'. Default is 1.
 
 Options:
   -h|--help       show this help text
@@ -40,6 +70,7 @@ USAGE
 # Deal with arguments
 recursive=0
 verbose=0
+max_depth=1
 while getopts :-:hr arg; do
   case ${arg} in
     -)
@@ -62,6 +93,8 @@ while getopts :-:hr arg; do
       esac;;    
     r)  recursive=1
         ;;
+    d)  max_depth=${OPTARG}
+        ;;        
     h)  Usage && exit 0
         ;;        
   esac
@@ -71,50 +104,54 @@ if [[ $# -lt 3 ]] ; then
   Usage && exit 0
 fi
 
+#-----------------------------------------------------------------------------
+# read args
 search_for=${@:$OPTIND:1}
 replace_with=${@:$OPTIND+1:1}
 search_dir=${@:$OPTIND+2:1}
 
-function search_string {
-  local file=${1}
-  local search=${2}
-  local replace=${3}
+#-----------------------------------------------------------------------------
+# check inputs
+if [[ -z "${search_for}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify string to be replaced"
+  exit 1
+fi
 
-  case `grep -rn "${search}" ${file} >/dev/null; echo $?` in
-    0)
-    # code if found
-    if [[ ${verbose} -eq 1 ]]; then
-      echo "replacing \"${search}\" with \"${replace}\" in \"${file}\""
-    fi
+if [[ -z "${replace_with}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify replacing string"
+  exit 1
+fi
 
-    perl -pi -e 's|'"${search}"'|'"${replace}"'|g' "${file}"
-    ;;
-    1)
-    # code if not found
-    ;;
-    *)
-    # code if an error occurred
-    echo "FAILURE: \"${file}\""
-    ;;
-  esac
-}
+if [[ -z "${search_dir}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify input file/directory to perform operation on"
+  exit 1
+fi
 
-if [[ -d ${search_dir} ]]; then
+#-----------------------------------------------------------------------------
+# check if input is directory
+if [[ -d "${search_dir}" ]]; then
   if [[ ${recursive} -eq 1 ]]; then
     if [[ ${verbose} -eq 1 ]]; then
       echo "Locating files"
     fi
     
-    search_files=($(find ${search_dir} -type f))
+    search_files=($(find "${search_dir}" -type f))
   else
-    search_files=($(find ${search_dir} -maxdepth 1 -type f))
+    search_files=($(find "${search_dir}" -maxdepth ${max_depth} -type f))
   fi
 
   for file in ${search_files[@]}; do
-    if [[ -f ${file} ]]; then
-      search_string ${file} ${search_for} ${replace_with}
+    if [[ -f "${file}" ]]; then
+      search_string "${file}" "${search_for}" "${replace_with}"
     fi
   done
 elif [[ -f ${search_dir} ]]; then
-  search_string ${search_dir} ${search_for} ${replace_with}
+  # input is file
+  search_string "${search_dir}" "${search_for}" "${replace_with}"
 fi
diff --git a/bin/call_spmbias b/bin/call_spmbias
--- a/bin/call_spmbias
+++ b/bin/call_spmbias
@@ -78,102 +78,163 @@ do
   esac
 done
 
+#-----------------------------------------------------------------------------
+# read args
 INPUT=${@:$OPTIND:1}
 OUTPUT=${@:$OPTIND+1:1}
 
 #-----------------------------------------------------------------------------
-# Define default LOG-path
-if [[ -z ${LOG} ]]; then
-  if [[ -z ${DIR_LOGS} ]]; then
-    LOG_DIR=${PWD}
-  else
-    LOG_DIR=${DIR_LOGS}
-  fi
+# check inputs
+if [[ ! -f "${INPUT}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Could not find input image \"${BOLD_GREEN}${INPUT}${RESET}\""
+  exit 1
 else
-  LOG_DIR=${LOG}
+  INPUT=$(readlink -f "${INPUT}")
 fi
 
-if [[ ! -d ${LOG_DIR} ]]; then
-  mkdir -p ${LOG_DIR}
+if [[ -z "${OUTPUT}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify output file"
+  exit 1
+fi
+
+#-----------------------------------------------------------------------------
+# Define default LOG-path
+if [[ -z "${LOG}" ]]; then
+  if [[ -z "${DIR_LOGS}" ]]; then
+    LOG_DIR="${PWD}"
+  else
+    LOG_DIR="${DIR_LOGS}"
+  fi
+else
+  LOG_DIR="${LOG}"
+fi
+
+if [[ ! -d "${LOG_DIR}" ]]; then
+  mkdir -p "${LOG_DIR}"
 fi
 
 #-----------------------------------------------------------------------------
 # Define default SPM-path
-if [[ -z ${SPM} ]]; then
-  if [[ -z ${SPM_PATH} ]]; then
+if [[ -z "${SPM}" ]]; then
+  if [[ -z "${SPM_PATH}" ]]; then
     echo
     print_line -
-    print_error_msg "$(basename ${0})" "SPM" "SPM_PATH-variable is empty. Set accordingly or use '-s <spm_path>' input.."
+    print_error_msg "$(basename ${0})" "SPM" "SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
     exit 1
   else
-    SPM_PATH=${SPM_PATH}
+    SPM_PATH="${SPM_PATH}"
   fi
 else
-  SPM_PATH=${SPM}
+  SPM_PATH="${SPM}"
 fi
 
 # double check if directory exists
-if [[ ! -d ${SPM_PATH} ]]; then
+if [[ ! -d "${SPM_PATH}" ]]; then
+  echo
+  print_line -
   print_error_msg "$(basename ${0})" "SPM" "Could not find SPM directory ${BOLD_GREEN}${SPM_PATH}${RESET}"
   exit 1
 fi
 
+#-----------------------------------------------------------------------------
 # if file specified is in current directory, add entire path
-INPUT=$(fetch_filepath ${INPUT})
-
-ext=$(fetch_extension ${INPUT})
+ext=$(fetch_extension "${INPUT}")
 if [[ ${ext} == "gz" ]]; then
-  in_file=$(dirname ${INPUT})/$(basename ${INPUT} .gz)
-  gunzip -fc ${INPUT} > ${in_file}
+  in_file="${INPUT%.gz}"
+  gunzip -fc "${INPUT}" > "${in_file}"
 else
-  in_file=${INPUT}
+  in_file="${INPUT}"
 fi
 
 #-----------------------------------------------------------------------------
 # Create new script
-new_script=$(dirname ${in_file})/spm_bias.m
-if [[ -f ${new_script} ]]; then
-  rm -r ${new_script}
+new_script=$(dirname "${in_file}")/spm_bias.m
+rm -r "${new_script}" 2>/dev/null
+
+# make output directory
+if [[ ! -d "$(dirname "${OUTPUT}")" ]]; then
+  mkdir -p "$(dirname "${OUTPUT}")"
 fi
 
-if [[ ! -d $(dirname ${OUTPUT}) ]]; then
-  mkdir -p $(dirname ${OUTPUT})
-fi
+#-----------------------------------------------------------------------------
+# check is mask exists
+mask_img=$(
+  find "$(dirname "${in_file}")" \
+  -type f \
+  -name "m$(basename "${in_file}")"* \
+  2>/dev/null
+)
+if [[ -z "${mask_img}" ]]; then
 
-mask_img=$(find $(dirname ${in_file}) -type f -name "m$(basename ${in_file})*" 2>/dev/null)
-if [[ -z ${mask_img} ]]; then
+  #-----------------------------------------------------------------------------
+  # make script
+  make_bias_script \
+    "${SPM_PATH}" \
+    "${in_file}" \
+    "${new_script}"
 
-  make_bias_script ${SPM_PATH} ${in_file} ${new_script}
-
+  #-----------------------------------------------------------------------------
   # call_matlab = in call_bashhelper
-  call_matlab ${new_script}
+  call_matlab "${new_script}"
 
-  mask_img=$(find $(dirname ${in_file}) -type f -name "m$(basename ${in_file})*" 2>/dev/null)
+  #-----------------------------------------------------------------------------
+  # look if masks was created
+  mask_img=$(
+    find "$(dirname "${in_file}")" \
+    -type f \
+    -name "m$(basename "${in_file}")"* \
+    2>/dev/null
+  )
   if [[ $? -ne 0 || -z "${mask_img}" ]]; then
     echo
     print_line -
     print_error_msg "$(basename ${0})" "make_bias_script"
     exit 1
   fi
-
 fi
 
+#-----------------------------------------------------------------------------
+# clean up
 if [[ ${RM} -eq 1 ]]; then
-  rm -r $(dirname ${in_file})/c*$(basename ${in_file}) *.mat 2>/dev/null
-  rm -r $(dirname ${in_file})/*seg8.mat 2>/dev/null
-  rm -r $(dirname ${in_file})/BiasField*
+  rm -r "${in_file%/*}/c*${in_file##*/}" *.mat 2>/dev/null
+  rm -r "${in_file%/*}/"*seg8.mat 2>/dev/null
+  rm -r "${in_file%/*}/BiasField"*
 fi
 
+#-----------------------------------------------------------------------------
 # Convert SPM's .nii-files to .nii.gz if the input file was nii.gz
-mask_img=$(find $(dirname ${in_file}) -type f -name "m$(basename ${in_file})*" 2>/dev/null)
-if [[ ! -z ${mask_img} ]]; then
+mask_img=$(
+  find "$(dirname "${in_file}")" \
+  -type f \
+  -name "m$(basename "${in_file}")"* \
+  2>/dev/null
+)
+if [[ ! -z "${mask_img}" ]]; then
   if [[ ${ext} == "gz" ]]; then
-    gzip -cf ${mask_img} > ${OUTPUT} 2>/dev/null
-    rm -r ${in_file} ${mask_img} ${INPUT} 2>/dev/null
+    gzip -cf "${mask_img}" > "${OUTPUT}" 2>/dev/null
+    rm -r "${in_file}" "${mask_img}" "${INPUT}" 2>/dev/null
   else
-    mv ${mask_img} ${OUTPUT}
+    mv "${mask_img}" "${OUTPUT}" 2>/dev/null
   fi
 fi
 
+#-----------------------------------------------------------------------------
 # copy header
-call_copyheader ${in_file} ${OUTPUT}
+cmd=(
+  call_copyheader
+  "${in_file}"
+  "${OUTPUT}"
+)
+
+# run
+eval "${cmd[@]}"
+if [[ $? -ne 0 ]]; then
+  echo 
+  print_line -
+  print_error_msg "$(basename ${0})" "${cmd[0]}"
+  exit 1
+fi
diff --git a/bin/call_spmphysio b/bin/call_spmphysio
--- a/bin/call_spmphysio
+++ b/bin/call_spmphysio
@@ -108,32 +108,51 @@ do
   esac
 done
 
+#-----------------------------------------------------------------------------
+# read args
 INPUT=${@:$OPTIND:1}
 OUTPUT=${@:$OPTIND+1:1}
 
 #-----------------------------------------------------------------------------
-# Define default SPM-path
-if [[ -z ${SPM} ]]; then
-  if [[ -z ${SPM_PATH} ]]; then
-    echo
-    print_line -
-    print_error_msg "$(basename ${0})" "SPM" "SPM_PATH-variable is empty. Set accordingly or use '-s <spm_path>' input.."
-    exit 1
-  else
-    SPM_PATH=${SPM_PATH}
-  fi
+# check inputs
+if [[ ! -f "${INPUT}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Could not find input image \"${BOLD_GREEN}${INPUT}${RESET}\""
+  exit 1
 else
-  SPM_PATH=${SPM}
+  INPUT=$(readlink -f "${INPUT}")
 fi
 
-# double check if directory exists
-if [[ ! -d ${SPM_PATH} ]]; then
-  print_error_msg "$(basename ${0})" "SPM" "Could not find SPM directory ${BOLD_GREEN}${SPM_PATH}${RESET}"
+if [[ -z "${OUTPUT}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" input "Please specify output file"
   exit 1
 fi
 
-# fetch full paths
-INPUT=$(fetch_filepath ${INPUT})
+#-----------------------------------------------------------------------------
+# Define default SPM-path
+if [[ -z "${SPM}" ]]; then
+  if [[ -z "${SPM_PATH}" ]]; then
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "SPM" "SPM_PATH-variable is empty. Either define it, or specify an SPM-path with \"-s <path/to/spm>\""
+    exit 1
+  else
+    SPM_PATH="${SPM_PATH}"
+  fi
+else
+  SPM_PATH="${SPM}"
+fi
+
+# double check if directory exists
+if [[ ! -d "${SPM_PATH}" ]]; then
+  echo
+  print_line -
+  print_error_msg "$(basename ${0})" "SPM" "Could not find SPM directory ${BOLD_GREEN}${SPM_PATH}${RESET}"
+  exit 1
+fi
 
 #-----------------------------------------------------------------------------
 # Fetch number of volumes
@@ -164,10 +183,10 @@ fi
 
 #-----------------------------------------------------------------------------
 # Fetch TR
-if [[ -z ${TR} ]]; then
+if [[ -z "${TR}" ]]; then
   TR=0.105
 else
-  TR=${TR}
+  TR="${TR}"
 fi
 
 #-----------------------------------------------------------------------------
@@ -180,23 +199,17 @@ fi
 
 #-----------------------------------------------------------------------------
 # Create new script
-new_script=$(dirname ${OUTPUT})/spm_physio.m
-if [[ -f ${new_script} ]]; then
-  rm -r ${new_script}
-fi
+output_dir="$(dirname "${OUTPUT}")"
+new_script="${output_dir}/spm_physio.m"
+rm -r "${new_script}" 2>/dev/null
 
-new_batch=$(dirname ${OUTPUT})/spm_physio_batch.m
-if [[ -f ${new_batch} ]]; then
-  rm -r ${new_batch}
-fi
+new_batch="${output_dir}/spm_physio_batch.m"
+rm -r "${new_batch}" 2>/dev/null
 
-if [[ ! -d $(dirname ${OUTPUT}) ]]; then
-  mkdir -p $(dirname ${OUTPUT})
+# make output directory
+if [[ ! -d "${output_dir}" ]]; then
+  mkdir -p "${output_dir}"
 fi
-
-#-----------------------------------------------------------------------------
-# fetch full paths in case only a filename was specified
-INPUT=$(fetch_filepath ${INPUT})
 
 #-----------------------------------------------------------------------------
 # Do some preprocessing with 'scanphyslog2bids' from Lukas Snoek:
@@ -213,7 +226,7 @@ if [[ ${RUN_PHYS} -eq 1 ]]; then
     --sf 496
     --triggermethod interpolate
     --outdir "$(dirname ${INPUT})"
-    ${MAKE_PLOTS}
+    "${MAKE_PLOTS}"
     --derivdir "$(dirname ${INPUT})"
   )
   
@@ -227,11 +240,11 @@ if [[ ${RUN_PHYS} -eq 1 ]]; then
   fi
 
   # fetch the output from scanphyslog2bids
-  PHYSIO_INPUT=$(dirname ${INPUT})/$(basename ${INPUT} .log).tsv.gz
+  PHYSIO_INPUT="${INPUT/.log/.tsv.gz}"
   input_type="BIDS"
 else
   input_type="RAW"
-  PHYSIO_INPUT=${INPUT}
+  PHYSIO_INPUT="${INPUT}"
 fi
 
 # echo input type
@@ -241,33 +254,53 @@ echo "Input = ${input_type}: ${PHYSIO_INPUT}"
 # Run TAPAS
 if [[ ${RUN_MATLAB} -eq 1 ]]; then
 
+  #-----------------------------------------------------------------------------
   # create the matlab script
-  make_physio_script ${SPM_PATH} ${PHYSIO_INPUT} ${TR} ${VOLS} ${OUTPUT} ${N_DUMMY} ${N_SLICES} ${new_script}
+  make_physio_script \
+    "${SPM_PATH}" \
+    "${PHYSIO_INPUT}" \
+    "${TR}" \
+    "${VOLS}" \
+    "${OUTPUT}" \
+    "${N_DUMMY}" \
+    "${N_SLICES}" \
+    "${new_script}"
+
   if [[ $? -ne 0 ]]; then
-    echo -e "${BOLD_RED}ERROR${RESET} in $(basename ${0}): make_physio_script exited with non-zero status"
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "make_physio_script"
     exit 1
   fi
 
   # execute the script with matlab
   echo "Initializing TAPAS"
 
-  log_file=$(dirname ${OUTPUT})/physlog.txt
-  if [ -f ${log_file} ]; then
-    rm -r ${log_file} 2>/dev/null
-  fi
+  log_file="${output_dir}/physlog.txt"
+  rm -r ${log_file} 2>/dev/null
 
+  #-----------------------------------------------------------------------------
   # run matlab
   call_matlab ${new_script} >> ${log_file}
 
   # check if matlab succeeded
-  ff=$(cat ${log_file} | grep "Failed: TAPAS PhysIO Toolbox" | cut -d"." -f2 | xargs | sed 's/\r$//')
-  if [[ ! -z ${ff} ]]; then
-    mv ${log_file} $(dirname ${INPUT})/$(basename ${INPUT} .log)_error.log
-    echo "ERROR: matlab exited with non-zero status"
+  ff=$(
+    cat "${log_file}" | \
+    grep "Failed: TAPAS PhysIO Toolbox" | \
+    cut -d"." -f2 | \
+    xargs | \
+    sed 's/\r$//'
+  )
+
+  if [[ ! -z "${ff}" ]]; then
+    mv "${log_file}" "${INPUT/.log/_error.log}"
+    echo
+    print_line -
+    print_error_msg "$(basename ${0})" "matlab"
     exit 1
   else
     echo "TAPAS completed!"
-    if [[ -f ${OUTPUT}.tsv ]]; then
+    if [[ -f "${OUTPUT}.tsv" ]]; then
 
       echo "Formatting output in human-readable csv-file"
       # save final dataframe
@@ -281,9 +314,9 @@ END
       python -c "$PYTHON_CODE"
 
       # only keep newly created file
-      if [[ -f ${OUTPUT}.csv ]]; then
-        echo "Wrote ${OUTPUT}.csv"
-        rm -r ${OUTPUT}.tsv ${OUTPUT}.mat 2>/dev/null
+      if [[ -f "${OUTPUT}.csv" ]]; then
+        echo -e "Wrote ${BOLD_GREEN}${OUTPUT}.csv${RESET}"
+        rm -r "${OUTPUT}.tsv" "${OUTPUT}.mat" 2>/dev/null
       fi
     fi
   fi
