sort TR before attempting slicetiming

diff --git a/bin/call_bids b/bin/call_bids
--- a/bin/call_bids
+++ b/bin/call_bids
@@ -662,30 +662,6 @@ if [[ ${PHYS_ONLY} -eq 0 ]]; then
                 echo "  Storing information from `basename ${par_f}` in json file"
                 pars_for_json --merge ${par_f} ${json_bids}
 
-                # check if we can add slicetimings
-                if [[ ${image} != "phase" ]]; then
-                  scan_mode=`read_par ${par_f} "Scan mode"`
-
-                  if [[ ${scan_mode} != "3D" ]]; then
-                    mb_factor=`read_json ${json_bids} MultiBandAccelerationFactor`
-                    if [[ -z ${mb_factor} ]]; then
-                      mb_factor=3
-                      mb_warning=1
-                      warning=1
-                      echo "  WARNING: defaulting to multiband factor 3 for slice-timings, please check if this is correct or put \"export MB_FACTOR=value\" in setup file!"
-                    fi
-
-                    tr=`read_json ${json_bids} RepetitionTime`
-                    n_slices=`read_par ${par_f} "Max. number of slices/locations"`
-                    call_slicetiming ${json_bids} ${tr} ${n_slices} ${mb_factor}
-
-                    if [[ $? -ne 0 ]]; then
-                      echo "ERROR in `basename ${0}`: call_slicetiming exited with non-zero code"
-                      exit 1
-                    fi
-                  fi
-                fi
-
                 # check if json file has RepetitionTime
                 rep_time=`cat ${json_bids} | grep "RepetitionTime"`
                 if [[ -z ${rep_time} ]]; then
@@ -701,6 +677,31 @@ if [[ ${PHYS_ONLY} -eq 0 ]]; then
                     if [ ${tr_hd} = "0.000000" ] ; then 
                       echo "  TR=0 in file header.. Setting to ${tr}"
                       call_settr ${ff} ${tr}
+                    fi
+                  fi
+                fi   
+
+                # check if we can add slicetimings
+                if [[ ${image} != "phase" ]]; then
+                  scan_mode=`read_par ${par_f} "Scan mode"`
+
+                  if [[ ${scan_mode} != "3D" ]]; then
+                    mb_factor=`read_json ${json_bids} MultiBandAccelerationFactor`
+                    if [[ -z ${mb_factor} ]]; then
+                      mb_factor=3
+                      mb_warning=1
+                      warning=1
+                      echo "  WARNING: defaulting to multiband factor 3 for slice-timings, please check if this is correct or put \"export MB_FACTOR=value\" in setup file!"
+                    fi
+
+                    tr=`read_json ${json_bids} RepetitionTime`
+                    n_slices=`read_par ${par_f} "Max. number of slices/locations"`
+                    cmd="call_slicetiming ${json_bids} ${tr} ${n_slices} ${mb_factor}"
+                    R
+
+                    if [[ $? -ne 0 ]]; then
+                      echo "ERROR in `basename ${0}`: call_slicetiming exited with non-zero code"
+                      exit 1
                     fi
                   fi
                 fi     
