homogenize intro, setup, and SoGE/SLURM

diff --git a/shell/spinoza_setup b/shell/spinoza_setup
--- a/shell/spinoza_setup
+++ b/shell/spinoza_setup
@@ -1,62 +1,11 @@
 #!/usr/bin/env bash
 
-export SETUP_FILE="`which spinoza_setup`"
-export SETUP_DIR="$(dirname ${SETUP_FILE})"
-export REPO_DIR="CH_REPO_DIR"
-export BIN_DIR="CH_BIN_DIR"
-
-#===================================================================================================
-# VARIABLES
-#===================================================================================================
-
-# MRI
-export MRI_SYSTEM="siemens" # "philips"
-
-# Project stuff
-export DIR_PROJECTS="/Users/heij/git/openfmri"
-export PROJECT="EPI"
-export TASK_SES1=("2R")
-export TASK_SES2="LR"
-export SUBJECT_PREFIX="sub-"
-export COMBINE_SEGMENTATIONS="weighted"
-export PATH_HOME=${DIR_PROJECTS}/logs
-export SEARCH_ANATOMICALS=("T2w" "FLAIR" "T1w")
-
-export PYBEST_SPACE="fsnative"
-export PYBEST_N_COMPS=20
-
-# DATA TYPE(S)
-export ACQ=("MPRAGE")  # or ("MP2RAGE" "MP2RAGEME")
-export DATA=${ACQ[0]}   # or MP2RAGEME/AVERAGE
-
-# phase encoding direction for BOLD; assume inverse for FMAP
-export PE_DIR_BOLD="AP"
-
-# If you have access to SGE, leave to SGE; otherwise change to e.g., LOCAL
-export PLACE="SGE"
-export SGE_QUEUE_LONG="long.q@jupiter"
-export SGE_QUEUE_SHORT="short.q@jupiter"
-export OMP_NUM_THREADS=1 
-export MKL_NUM_THREADS=1
-export OPENBLAS_NUM_THREADS=1
-
-# MATLAB
-export MRRECON=/packages/matlab/toolbox/MRecon/3.0.541  
-export MATLAB_CMD="matlab -nosplash -nodisplay -batch" # find with 'which matlab'
-export SPM_PATH=${PATH_HOME}/spm12    
-export SKIP_LINES=34                               
-
-# fMRIPREP
-export MRIQC_SIMG=/packages/singularity_containers/containers_bids-mriqc--23.0.1.simg
-export FPREP_SIMG=/packages/singularity_containers/containers_bids-fmriprep--20.2.5.simg
-export FPREP_OUT_SPACES="fsnative func"
-export FPREP_BINDING="/data1/projects"                                          # binding directory for singularity image
-export CIFTI=""                                                                 # leave empty if you don't want cifti output
-export DO_SYN=0                                                                 # set to zero if you do not want additional syn-distortion correction
-export BOLD_T1W_INIT="register"                                                 # default = register; for partial FOV, set to 'header'
-export FS_LICENSE=${REPO_DIR}/misc/license.txt                                  # this thing needs to be along the FPREP_BINDING path!
-
-# PYBEST
+if [[ -f ${CONFIG_FILE} ]]; then
+  source ${CONFIG_FILE}
+else
+  echo "ERROR: could not source \"${CONFIG_FILE}\""
+  exit 1
+fi
 
 # For DATA == AVERAGE we'll need multiple acquisitions
 if [[ ${DATA} == "AVERAGE" ]]; then
